//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/solve/blocks/n/VerticalBlock.java
//
//  Created by Thomas on 7/25/13.
//

#ifndef _TuxkidsTuxblocksCoreSolveBlocksNVerticalBlock_H_
#define _TuxkidsTuxblocksCoreSolveBlocksNVerticalBlock_H_

#import "JreEmulation.h"
#include "tuxkids/tuxblocks/core/solve/blocks/n/ModifierBlock.h"

@interface TuxkidsTuxblocksCoreSolveBlocksNVerticalBlock : TuxkidsTuxblocksCoreSolveBlocksNModifierBlock {
}

- (id)initWithInt:(int)value;
- (BOOL)canSimplify;
- (BOOL)canReduce;
- (BOOL)canReleaseWithBOOL:(BOOL)openBlock;
@end

#endif // _TuxkidsTuxblocksCoreSolveBlocksNVerticalBlock_H_
