//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/game/trans/PageTurnTransition.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !TripleplayGameTransPageTurnTransition_RESTRICT
#define TripleplayGameTransPageTurnTransition_INCLUDE_ALL 1
#endif
#undef TripleplayGameTransPageTurnTransition_RESTRICT

#if !defined (_TripleplayGameTransPageTurnTransition_) && (TripleplayGameTransPageTurnTransition_INCLUDE_ALL || TripleplayGameTransPageTurnTransition_INCLUDE)
#define _TripleplayGameTransPageTurnTransition_

@class TripleplayGameScreen;
@class TripleplayShadersRotateYShader;
@class TripleplayUtilInterpolator;
@protocol PlaynCoreImmediateLayer;

#define TripleplayGameTransInterpedTransition_RESTRICT 1
#define TripleplayGameTransInterpedTransition_INCLUDE 1
#include "tripleplay/game/trans/InterpedTransition.h"

@interface TripleplayGameTransPageTurnTransition : TripleplayGameTransInterpedTransition {
 @public
  float _alpha_;
  BOOL _close_;
  TripleplayGameScreen *_toflip_;
  id<PlaynCoreImmediateLayer> _shadow_;
  TripleplayShadersRotateYShader *_shader_;
}

@property (nonatomic, assign) float _alpha;
@property (nonatomic, assign) BOOL _close;
@property (nonatomic, strong) TripleplayGameScreen *_toflip;
@property (nonatomic, strong) id<PlaynCoreImmediateLayer> _shadow;
@property (nonatomic, strong) TripleplayShadersRotateYShader *_shader;

- (TripleplayGameTransPageTurnTransition *)close;
- (void)init__WithTripleplayGameScreen:(TripleplayGameScreen *)oscreen
              withTripleplayGameScreen:(TripleplayGameScreen *)nscreen OBJC_METHOD_FAMILY_NONE;
- (BOOL)updateWithTripleplayGameScreen:(TripleplayGameScreen *)oscreen
              withTripleplayGameScreen:(TripleplayGameScreen *)nscreen
                             withFloat:(float)elapsed;
- (void)completeWithTripleplayGameScreen:(TripleplayGameScreen *)oscreen
                withTripleplayGameScreen:(TripleplayGameScreen *)nscreen;
- (float)defaultDuration;
- (TripleplayUtilInterpolator *)defaultInterpolator;
- (void)updateAngleWithFloat:(float)elapsed;
- (id)init;
@end
#endif

#if !defined (_TripleplayGameTransPageTurnTransition_$1_) && (TripleplayGameTransPageTurnTransition_INCLUDE_ALL || TripleplayGameTransPageTurnTransition_$1_INCLUDE)
#define _TripleplayGameTransPageTurnTransition_$1_

@class TripleplayGameTransPageTurnTransition;
@protocol PlaynCoreSurface;

#define PlaynCoreImmediateLayer_RESTRICT 1
#define PlaynCoreImmediateLayer_Renderer_INCLUDE 1
#include "playn/core/ImmediateLayer.h"

@interface TripleplayGameTransPageTurnTransition_$1 : NSObject < PlaynCoreImmediateLayer_Renderer > {
 @public
  TripleplayGameTransPageTurnTransition *this$0_;
  float val$fwidth_;
  float val$fheight_;
}

@property (nonatomic, strong) TripleplayGameTransPageTurnTransition *this$0;
@property (nonatomic, assign) float val$fwidth;
@property (nonatomic, assign) float val$fheight;

- (void)renderWithPlaynCoreSurface:(id<PlaynCoreSurface>)surf;
- (id)initWithTripleplayGameTransPageTurnTransition:(TripleplayGameTransPageTurnTransition *)outer$
                                          withFloat:(float)capture$0
                                          withFloat:(float)capture$1;
@end
#endif
