//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/canvas/LayerCanvas.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCoreCanvasLayerCanvas_RESTRICT
#define PlaynCoreCanvasLayerCanvas_INCLUDE_ALL 1
#endif
#undef PlaynCoreCanvasLayerCanvas_RESTRICT

#if !defined (_PlaynCoreCanvasLayerCanvas_) && (PlaynCoreCanvasLayerCanvas_INCLUDE_ALL || PlaynCoreCanvasLayerCanvas_INCLUDE)
#define _PlaynCoreCanvasLayerCanvas_

@protocol PlaynCoreCanvas;
@protocol PlaynCoreInternalTransform;

#define PlaynCoreAbstractLayer_RESTRICT 1
#define PlaynCoreAbstractLayer_INCLUDE 1
#include "playn/core/AbstractLayer.h"

@interface PlaynCoreCanvasLayerCanvas : PlaynCoreAbstractLayer {
}

- (void)paintWithPlaynCoreCanvas:(id<PlaynCoreCanvas>)canvas
                       withFloat:(float)parentAlpha;
- (id)initWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>)xform;
- (void)transformWithPlaynCoreCanvas:(id<PlaynCoreCanvas>)canvas;
@end
#endif
