//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/ImageIcon.java
//
//  Created by Thomas on 7/10/13.
//

#import "java/lang/Throwable.h"
#import "playn/core/Graphics.h"
#import "playn/core/Image.h"
#import "playn/core/ImageLayer.h"
#import "playn/core/Layer.h"
#import "playn/core/PlayN.h"
#import "playn/core/util/Callback.h"
#import "tripleplay/ui/ImageIcon.h"

@implementation TripleplayUiImageIcon

@synthesize _image = _image_;

- (id)initWithPlaynCoreImage:(id<PlaynCoreImage>)image {
  if ((self = [super init])) {
    _image_ = image;
  }
  return self;
}

- (float)width {
  return [((id<PlaynCoreImage>) NIL_CHK(_image_)) width];
}

- (float)height {
  return [((id<PlaynCoreImage>) NIL_CHK(_image_)) height];
}

- (id<PlaynCoreLayer>)render {
  return [((id<PlaynCoreGraphics>) [PlaynCorePlayN graphics]) createImageLayerWithPlaynCoreImage:_image_];
}

- (void)addCallbackWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)callback {
  [((id<PlaynCoreImage>) NIL_CHK(_image_)) addCallbackWithPlaynCoreUtilCallback:[[TripleplayUiImageIcon_$1 alloc] initWithTripleplayUiImageIcon:self withPlaynCoreUtilCallback:callback]];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiImageIcon *typedCopy = (TripleplayUiImageIcon *) copy;
  typedCopy._image = _image_;
}

@end
@implementation TripleplayUiImageIcon_$1

@synthesize this$0 = this$0_;
@synthesize val$callback = val$callback_;

- (void)onSuccessWithId:(id<PlaynCoreImage>)result {
  [((id<PlaynCoreUtilCallback>) NIL_CHK(val$callback_)) onSuccessWithId:this$0_];
}

- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)cause {
  [((id<PlaynCoreUtilCallback>) NIL_CHK(val$callback_)) onFailureWithJavaLangThrowable:cause];
}

- (id)initWithTripleplayUiImageIcon:(TripleplayUiImageIcon *)outer$
          withPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)capture$0 {
  if ((self = [super init])) {
    this$0_ = outer$;
    val$callback_ = capture$0;
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiImageIcon_$1 *typedCopy = (TripleplayUiImageIcon_$1 *) copy;
  typedCopy.this$0 = this$0_;
  typedCopy.val$callback = val$callback_;
}

@end
