//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/Log.java
//
//  Created by Thomas on 7/10/13.
//

#import "tripleplay/ui/Log.h"
#import "tripleplay/util/Logger.h"

@implementation TripleplayUiLog

static TripleplayUtilLogger * TripleplayUiLog_log_;

+ (TripleplayUtilLogger *)log {
  return TripleplayUiLog_log_;
}

- (id)init {
  return [super init];
}

+ (void)initialize {
  if (self == [TripleplayUiLog class]) {
    TripleplayUiLog_log_ = [[TripleplayUtilLogger alloc] initWithNSString:@"tpui"];
  }
}

@end
