//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/SizableGroup.java
//
//  Created by Thomas on 7/25/13.
//

#include "pythagoras/f/IDimension.h"
#include "react/Connection.h"
#include "react/UnitSlot.h"
#include "tripleplay/ui/Element.h"
#include "tripleplay/ui/Layout.h"
#include "tripleplay/ui/SizableGroup.h"
#include "tripleplay/util/DimensionValue.h"

@implementation TripleplayUiSizableGroup

@synthesize preferredSize = preferredSize_;

- (id)initWithTripleplayUiLayout:(TripleplayUiLayout *)layout {
  return [self initTripleplayUiSizableGroupWithTripleplayUiLayout:layout withFloat:0 withFloat:0];
}

- (id)initWithTripleplayUiLayout:(TripleplayUiLayout *)layout
       withPythagorasFIDimension:(id<PythagorasFIDimension>)size {
  return [self initTripleplayUiSizableGroupWithTripleplayUiLayout:layout withFloat:[((id<PythagorasFIDimension>) nil_chk(size)) width] withFloat:[((id<PythagorasFIDimension>) nil_chk(size)) height]];
}

- (id)initTripleplayUiSizableGroupWithTripleplayUiLayout:(TripleplayUiLayout *)layout
                                               withFloat:(float)wid
                                               withFloat:(float)hei {
  if ((self = [super initWithTripleplayUiLayout:layout])) {
    preferredSize_ = [[TripleplayUtilDimensionValue alloc] initWithFloat:0 withFloat:0];
    [((TripleplayUtilDimensionValue *) nil_chk(preferredSize_)) updateWithFloat:wid withFloat:hei];
    (void) [((TripleplayUtilDimensionValue *) nil_chk(preferredSize_)) connectWithReactValueView_Listener:[self invalidateSlot]];
  }
  return self;
}

- (id)initWithTripleplayUiLayout:(TripleplayUiLayout *)layout
                       withFloat:(float)wid
                       withFloat:(float)hei {
  return [self initTripleplayUiSizableGroupWithTripleplayUiLayout:layout withFloat:wid withFloat:hei];
}

- (TripleplayUiElement_LayoutData *)createLayoutDataWithFloat:(float)hintX
                                                    withFloat:(float)hintY {
  return [[TripleplayUiElement_SizableLayoutData alloc] initWithTripleplayUiElement:self withTripleplayUiElement_LayoutData:[super createLayoutDataWithFloat:hintX withFloat:hintY] withPythagorasFIDimension:[((TripleplayUtilDimensionValue *) nil_chk(preferredSize_)) get]];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiSizableGroup *typedCopy = (TripleplayUiSizableGroup *) copy;
  typedCopy.preferredSize = preferredSize_;
}

@end
