//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/sound/MultiClip.java
//
//  Created by Thomas on 7/10/13.
//

#import "java/util/ArrayList.h"
#import "java/util/Iterator.h"
#import "java/util/List.h"
#import "playn/core/PlayN.h"
#import "tripleplay/sound/Clip.h"
#import "tripleplay/sound/MultiClip.h"
#import "tripleplay/sound/SoundBoard.h"

@implementation TripleplaySoundMultiClip

@synthesize _board = _board_;
@synthesize _path = _path_;
@synthesize _reserveCopies = _reserveCopies_;
@synthesize _duration = _duration_;
@synthesize _copies = _copies_;

- (id)initWithTripleplaySoundSoundBoard:(TripleplaySoundSoundBoard *)board
                           withNSString:(NSString *)path
                                withInt:(int)reserveCopies
                              withFloat:(float)duration {
  if ((self = [super init])) {
    _copies_ = [[JavaUtilArrayList alloc] init];
    _board_ = board;
    _path_ = path;
    _reserveCopies_ = reserveCopies;
    _duration_ = duration * 1000;
  }
  return self;
}

- (id<TripleplaySoundMultiClip_Copy>)reserve {
  double now = [PlaynCorePlayN currentTime];
  for (int ii = 0, ll = [((id<JavaUtilList>) NIL_CHK(_copies_)) size]; ii < ll; ii++) {
    TripleplaySoundMultiClip_CopyImpl *copy_ = ((TripleplaySoundMultiClip_CopyImpl *) [((id<JavaUtilList>) NIL_CHK(_copies_)) getWithInt:ii]);
    if (((TripleplaySoundMultiClip_CopyImpl *) NIL_CHK(copy_)).releaseTime < now) {
      return ((TripleplaySoundMultiClip_CopyImpl *) [((id<JavaUtilList>) NIL_CHK(_copies_)) removeWithInt:ii]);
    }
  }
  return [[TripleplaySoundMultiClip_CopyImpl alloc] initWithTripleplaySoundMultiClip:self];
}

- (void)release__ {
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((id<JavaUtilList>) NIL_CHK(_copies_)) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      TripleplaySoundMultiClip_CopyImpl *copy_ = ((TripleplaySoundMultiClip_CopyImpl *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      [((id<TripleplaySoundClip>) NIL_CHK(copy_.sound)) release__];
    }
  }
  [((id<JavaUtilList>) NIL_CHK(_copies_)) clear];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplaySoundMultiClip *typedCopy = (TripleplaySoundMultiClip *) copy;
  typedCopy._board = _board_;
  typedCopy._path = _path_;
  typedCopy._reserveCopies = _reserveCopies_;
  typedCopy._duration = _duration_;
  typedCopy._copies = _copies_;
}

@end
@implementation TripleplaySoundMultiClip_CopyImpl

@synthesize this$0 = this$0_;
@synthesize sound = sound_;
@synthesize releaseTime = releaseTime_;

- (float)volume {
  return [((id<TripleplaySoundClip>) NIL_CHK(sound_)) volume];
}

- (void)setVolumeWithFloat:(float)volume {
  [((id<TripleplaySoundClip>) NIL_CHK(sound_)) setVolumeWithFloat:volume];
}

- (void)play {
  [((id<TripleplaySoundClip>) NIL_CHK(sound_)) play];
  if ([((id<JavaUtilList>) NIL_CHK(this$0_._copies)) size] < this$0_._reserveCopies) {
    releaseTime_ = [PlaynCorePlayN currentTime] + this$0_._duration;
    [((id<JavaUtilList>) NIL_CHK(this$0_._copies)) addWithId:self];
  }
}

- (void)release__ {
  if ([((id<JavaUtilList>) NIL_CHK(this$0_._copies)) size] < this$0_._reserveCopies) {
    releaseTime_ = [PlaynCorePlayN currentTime];
    [((id<JavaUtilList>) NIL_CHK(this$0_._copies)) addWithId:self];
  }
}

- (void)stop {
  [((id<TripleplaySoundClip>) NIL_CHK(sound_)) stop];
  releaseTime_ = 0;
}

- (BOOL)isPlaying {
  return [((id<TripleplaySoundClip>) NIL_CHK(sound_)) isPlaying];
}

- (id)initWithTripleplaySoundMultiClip:(TripleplaySoundMultiClip *)outer$ {
  if ((self = [super init])) {
    this$0_ = outer$;
    sound_ = [((TripleplaySoundSoundBoard *) NIL_CHK(outer$._board)) getClipWithNSString:outer$._path];
    {
      [((id<TripleplaySoundClip>) NIL_CHK(sound_)) setVolumeWithFloat:1];
      [((id<TripleplaySoundClip>) NIL_CHK(sound_)) preload];
    }
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplaySoundMultiClip_CopyImpl *typedCopy = (TripleplaySoundMultiClip_CopyImpl *) copy;
  typedCopy.this$0 = this$0_;
  typedCopy.sound = sound_;
  typedCopy.releaseTime = releaseTime_;
}

@end
