//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/Effector.java
//
//  Created by Thomas on 7/10/13.
//

#import "IOSFloatArray.h"
#import "tripleplay/particle/Effector.h"

@implementation TripleplayParticleEffector

- (void)applyWithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
             withInt:(int)start
           withFloat:(float)now
           withFloat:(float)dt {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (id)init {
  return [super init];
}

@end
