//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/Generator.java
//
//  Created by Thomas on 7/10/13.
//

@class TripleplayParticleEmitter;

#import "JreEmulation.h"

@interface TripleplayParticleGenerator : NSObject {
}

+ (TripleplayParticleGenerator *)NOOP;
+ (void)setNOOP:(TripleplayParticleGenerator *)NOOP;
+ (TripleplayParticleGenerator *)impulseWithInt:(int)particles;
+ (TripleplayParticleGenerator *)constantWithFloat:(float)particlesPerSecond;
- (BOOL)generateWithTripleplayParticleEmitter:(TripleplayParticleEmitter *)emitter
                                    withFloat:(float)now
                                    withFloat:(float)dt;
- (id)init;
@end

@interface TripleplayParticleGenerator_$1 : TripleplayParticleGenerator {
}

- (BOOL)generateWithTripleplayParticleEmitter:(TripleplayParticleEmitter *)emitter
                                    withFloat:(float)now
                                    withFloat:(float)dt;
- (id)init;
@end

@interface TripleplayParticleGenerator_$2 : TripleplayParticleGenerator {
 @public
  int val$particles_;
}

@property (nonatomic, assign) int val$particles;

- (BOOL)generateWithTripleplayParticleEmitter:(TripleplayParticleEmitter *)emitter
                                    withFloat:(float)now
                                    withFloat:(float)dt;
- (id)initWithInt:(int)capture$0;
@end

@interface TripleplayParticleGenerator_$3 : TripleplayParticleGenerator {
 @public
  float _secondsPerParticle_;
  float _accum_;
  float val$particlesPerSecond_;
}

@property (nonatomic, assign) float _secondsPerParticle;
@property (nonatomic, assign) float _accum;
@property (nonatomic, assign) float val$particlesPerSecond;

- (BOOL)generateWithTripleplayParticleEmitter:(TripleplayParticleEmitter *)emitter
                                    withFloat:(float)now
                                    withFloat:(float)dt;
- (id)initWithFloat:(float)capture$0;
@end
