//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/ConcurrentModificationException.java
//
//  Created by tball on 6/22/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaUtilConcurrentModificationException_serialVersionUID -3666751008965953603

@interface JavaUtilConcurrentModificationException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
