//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/Stack.java
//
//  Created by tball on 6/22/13.
//

#import "JreEmulation.h"
#import "java/util/Vector.h"

#define JavaUtilStack_serialVersionUID 1224463164541339165

@interface JavaUtilStack : JavaUtilVector {
}

- (id)init;
- (BOOL)empty;
- (id)peek;
- (id)pop;
- (id)pushWithId:(id)object;
- (int)searchWithId:(id)o;
@end
