//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/gl/LayerGL.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCoreGlLayerGL_RESTRICT
#define PlaynCoreGlLayerGL_INCLUDE_ALL 1
#endif
#undef PlaynCoreGlLayerGL_RESTRICT

#if !defined (_PlaynCoreGlLayerGL_) && (PlaynCoreGlLayerGL_INCLUDE_ALL || PlaynCoreGlLayerGL_INCLUDE)
#define _PlaynCoreGlLayerGL_

@class PlaynCoreGlGLContext;
@class PlaynCoreGlGLShader;
@protocol PlaynCoreInternalTransform;
@protocol PlaynCoreLayer;

#define PlaynCoreAbstractLayer_RESTRICT 1
#define PlaynCoreAbstractLayer_INCLUDE 1
#include "playn/core/AbstractLayer.h"

@interface PlaynCoreGlLayerGL : PlaynCoreAbstractLayer {
 @public
  id<PlaynCoreInternalTransform> savedLocal_;
  PlaynCoreGlGLContext *ctx_;
  PlaynCoreGlGLShader *shader_;
}

@property (nonatomic, strong) id<PlaynCoreInternalTransform> savedLocal;
@property (nonatomic, strong) PlaynCoreGlGLContext *ctx;
@property (nonatomic, strong) PlaynCoreGlGLShader *shader;

- (id<PlaynCoreLayer>)setShaderWithPlaynCoreGlGLShader:(PlaynCoreGlGLShader *)shader;
- (void)destroy;
- (id)initWithPlaynCoreGlGLContext:(PlaynCoreGlGLContext *)ctx;
- (id<PlaynCoreInternalTransform>)localTransformWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>)parentTransform;
- (void)paintWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>)curTransform
                                    withInt:(int)curTint
                    withPlaynCoreGlGLShader:(PlaynCoreGlGLShader *)curShader;
@end
#endif
