//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/util/SingularMatrixException.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasUtilSingularMatrixException_RESTRICT
#define PythagorasUtilSingularMatrixException_INCLUDE_ALL 1
#endif
#undef PythagorasUtilSingularMatrixException_RESTRICT

#if !defined (_PythagorasUtilSingularMatrixException_) && (PythagorasUtilSingularMatrixException_INCLUDE_ALL || PythagorasUtilSingularMatrixException_INCLUDE)
#define _PythagorasUtilSingularMatrixException_

#define JavaLangRuntimeException_RESTRICT 1
#define JavaLangRuntimeException_INCLUDE 1
#include "java/lang/RuntimeException.h"

@interface PythagorasUtilSingularMatrixException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)message;
@end
#endif
