//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/util/Input.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !TripleplayUtilInput_RESTRICT
#define TripleplayUtilInput_INCLUDE_ALL 1
#endif
#undef TripleplayUtilInput_RESTRICT
#if TripleplayUtilInput_Reactor_$1_INCLUDE
#define TripleplayUtilInput_Registration_INCLUDE 1
#endif
#if TripleplayUtilInput_SizedLayerRegion_INCLUDE
#define TripleplayUtilInput_Region_INCLUDE 1
#endif
#if TripleplayUtilInput_LayerRegion_INCLUDE
#define TripleplayUtilInput_Region_INCLUDE 1
#endif
#if TripleplayUtilInput_BoundsRegion_INCLUDE
#define TripleplayUtilInput_Region_INCLUDE 1
#endif
#if TripleplayUtilInput_ScreenRegion_INCLUDE
#define TripleplayUtilInput_Region_INCLUDE 1
#endif

#if !defined (_TripleplayUtilInput_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_INCLUDE)
#define _TripleplayUtilInput_

@class TripleplayUtilInput_Region;
@protocol PlaynCoreLayer;
@protocol PlaynCoreLayer_HasSize;
@protocol PythagorasFIRectangle;
@protocol TripleplayUtilInput_Registration;

@interface TripleplayUtilInput : NSObject {
}

- (id<TripleplayUtilInput_Registration>)register__WithTripleplayUtilInput_Region:(TripleplayUtilInput_Region *)region
                                                                          withId:(id)listener;
- (id<TripleplayUtilInput_Registration>)register__WithId:(id)listener;
- (id<TripleplayUtilInput_Registration>)register__WithPythagorasFIRectangle:(id<PythagorasFIRectangle>)bounds
                                                                     withId:(id)listener;
- (id<TripleplayUtilInput_Registration>)register__WithPlaynCoreLayer:(id<PlaynCoreLayer>)layer
                                           withPythagorasFIRectangle:(id<PythagorasFIRectangle>)bounds
                                                              withId:(id)listener;
- (id<TripleplayUtilInput_Registration>)register__WithPlaynCoreLayer_HasSize:(id<PlaynCoreLayer_HasSize>)layer
                                                                      withId:(id)listener;
- (id)init;
@end
#endif

#if !defined (_TripleplayUtilInput_Region_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_Region_INCLUDE)
#define _TripleplayUtilInput_Region_

@protocol PythagorasFIPoint;

@interface TripleplayUtilInput_Region : NSObject {
}

- (BOOL)canTrigger;
- (BOOL)hasExpired;
- (BOOL)hitTestWithPythagorasFIPoint:(id<PythagorasFIPoint>)p;
- (id)init;
@end
#endif

#if !defined (_TripleplayUtilInput_ScreenRegion_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_ScreenRegion_INCLUDE)
#define _TripleplayUtilInput_ScreenRegion_

@protocol PythagorasFIPoint;

@interface TripleplayUtilInput_ScreenRegion : TripleplayUtilInput_Region {
}

- (BOOL)hitTestWithPythagorasFIPoint:(id<PythagorasFIPoint>)p;
- (id)init;
@end
#endif

#if !defined (_TripleplayUtilInput_BoundsRegion_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_BoundsRegion_INCLUDE)
#define _TripleplayUtilInput_BoundsRegion_

@protocol PythagorasFIPoint;
@protocol PythagorasFIRectangle;

@interface TripleplayUtilInput_BoundsRegion : TripleplayUtilInput_Region {
 @public
  id<PythagorasFIRectangle> _bounds_;
}

@property (nonatomic, strong) id<PythagorasFIRectangle> _bounds;

- (id)initWithPythagorasFIRectangle:(id<PythagorasFIRectangle>)bounds;
- (BOOL)hitTestWithPythagorasFIPoint:(id<PythagorasFIPoint>)p;
@end
#endif

#if !defined (_TripleplayUtilInput_LayerRegion_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_LayerRegion_INCLUDE)
#define _TripleplayUtilInput_LayerRegion_

@protocol PlaynCoreLayer;
@protocol PythagorasFIPoint;
@protocol PythagorasFIRectangle;

@interface TripleplayUtilInput_LayerRegion : TripleplayUtilInput_Region {
 @public
  id<PlaynCoreLayer> _layer_;
  id<PythagorasFIRectangle> _bounds_;
}

@property (nonatomic, strong) id<PlaynCoreLayer> _layer;
@property (nonatomic, strong) id<PythagorasFIRectangle> _bounds;

- (id)initWithPlaynCoreLayer:(id<PlaynCoreLayer>)layer
   withPythagorasFIRectangle:(id<PythagorasFIRectangle>)bounds;
- (BOOL)canTrigger;
- (BOOL)hasExpired;
- (BOOL)hitTestWithPythagorasFIPoint:(id<PythagorasFIPoint>)p;
@end
#endif

#if !defined (_TripleplayUtilInput_SizedLayerRegion_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_SizedLayerRegion_INCLUDE)
#define _TripleplayUtilInput_SizedLayerRegion_

@protocol PlaynCoreLayer_HasSize;
@protocol PythagorasFIPoint;

@interface TripleplayUtilInput_SizedLayerRegion : TripleplayUtilInput_Region {
 @public
  id<PlaynCoreLayer_HasSize> _layer_;
}

@property (nonatomic, strong) id<PlaynCoreLayer_HasSize> _layer;

- (id)initWithPlaynCoreLayer_HasSize:(id<PlaynCoreLayer_HasSize>)layer;
- (BOOL)canTrigger;
- (BOOL)hasExpired;
- (BOOL)hitTestWithPythagorasFIPoint:(id<PythagorasFIPoint>)p;
@end
#endif

#if !defined (_TripleplayUtilInput_Reactor_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_Reactor_INCLUDE)
#define _TripleplayUtilInput_Reactor_

@class TripleplayUtilInput_Region;
@protocol JavaUtilList;
@protocol PlaynCoreEvents_Position;
@protocol TripleplayUtilInput_Registration;

@interface TripleplayUtilInput_Reactor : NSObject {
 @public
  id<JavaUtilList> _reactions_;
}

@property (nonatomic, strong) id<JavaUtilList> _reactions;

- (id)hitTestWithPlaynCoreEvents_Position:(id<PlaynCoreEvents_Position>)event;
- (id<TripleplayUtilInput_Registration>)register__WithTripleplayUtilInput_Region:(TripleplayUtilInput_Region *)region
                                                                          withId:(id)listener;
- (id)init;
@end
#endif

#if !defined (_TripleplayUtilInput_Registration_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_Registration_INCLUDE)
#define _TripleplayUtilInput_Registration_

@protocol TripleplayUtilInput_Registration < NSObject, JavaObject >
- (void)cancel;
@end
#endif

#if !defined (_TripleplayUtilInput_Reactor_$1_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_Reactor_$1_INCLUDE)
#define _TripleplayUtilInput_Reactor_$1_

@class TripleplayUtilInput_Reaction;
@class TripleplayUtilInput_Reactor;

@interface TripleplayUtilInput_Reactor_$1 : NSObject < TripleplayUtilInput_Registration > {
 @public
  TripleplayUtilInput_Reactor *this$0_;
  TripleplayUtilInput_Reaction *val$reaction_;
}

@property (nonatomic, strong) TripleplayUtilInput_Reactor *this$0;
@property (nonatomic, strong) TripleplayUtilInput_Reaction *val$reaction;

- (void)cancel;
- (id)initWithTripleplayUtilInput_Reactor:(TripleplayUtilInput_Reactor *)outer$
         withTripleplayUtilInput_Reaction:(TripleplayUtilInput_Reaction *)capture$0;
@end
#endif

#if !defined (_TripleplayUtilInput_Reaction_) && (TripleplayUtilInput_INCLUDE_ALL || TripleplayUtilInput_Reaction_INCLUDE)
#define _TripleplayUtilInput_Reaction_

@class TripleplayUtilInput_Region;

@interface TripleplayUtilInput_Reaction : NSObject {
 @public
  TripleplayUtilInput_Region *region_;
  id listener_;
}

@property (nonatomic, strong) TripleplayUtilInput_Region *region;
@property (nonatomic, strong) id listener;

- (id)initWithTripleplayUtilInput_Region:(TripleplayUtilInput_Region *)region
                                  withId:(id)listener;
@end
#endif
