//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/defense/tower/Zapper.java
//
//  Created by Thomas on 7/26/13.
//

#include "java/lang/Math.h"
#include "playn/core/Canvas.h"
#include "playn/core/CanvasImage.h"
#include "playn/core/Graphics.h"
#include "playn/core/Image.h"
#include "playn/core/PlayN.h"
#include "pythagoras/f/Vector.h"
#include "tripleplay/util/Colors.h"
#include "tuxkids/tuxblocks/core/defense/projectile/Lightning.h"
#include "tuxkids/tuxblocks/core/defense/projectile/Projectile.h"
#include "tuxkids/tuxblocks/core/defense/tower/Tower.h"
#include "tuxkids/tuxblocks/core/defense/tower/Zapper.h"

@implementation TuxkidsTuxblocksCoreDefenseTowerZapper

@synthesize projectileStart_ = projectileStart__;

- (int)rows {
  return 1;
}

- (int)cols {
  return 1;
}

- (float)damage {
  return 8;
}

- (int)fireRate {
  return 1500;
}

- (float)range {
  return 7;
}

- (TuxkidsTuxblocksCoreDefenseProjectileProjectile *)createProjectile {
  return [[TuxkidsTuxblocksCoreDefenseProjectileLightning alloc] initWithInt:4 withFloat:0.6f withFloat:0.6f];
}

- (TuxkidsTuxblocksCoreDefenseTowerTower *)copy__ OBJC_METHOD_FAMILY_NONE {
  return [[TuxkidsTuxblocksCoreDefenseTowerZapper alloc] init];
}

- (NSString *)name {
  return @"Zapper";
}

- (int)cost {
  return 10;
}

- (int)commonness {
  return 1;
}

- (PythagorasFVector *)projectileStart {
  (void) [((PythagorasFVector *) nil_chk(projectileStart__)) setWithFloat:((PythagorasFVector *) nil_chk([self position])).x_ withFloat:[((PythagorasFVector *) nil_chk([self position])) y] - [self height] * 0.4f];
  return projectileStart__;
}

- (id<PlaynCoreImage>)createImageWithFloat:(float)cellSize
                                   withInt:(int)color {
  int width = (int) (cellSize * [self cols]), height = (int) (cellSize * [self rows] * 1.3f);
  int padding = (int) (cellSize * 0.1f);
  int rad = (int) ([JavaLangMath minWithInt:width withInt:height] * 0.1f);
  id<PlaynCoreCanvasImage> image = [((id<PlaynCoreGraphics>) nil_chk([PlaynCorePlayN graphics])) createImageWithFloat:width withFloat:height];
  (void) [((id<PlaynCoreCanvas>) nil_chk([((id<PlaynCoreCanvasImage>) nil_chk(image)) canvas])) setFillColorWithInt:color];
  (void) [((id<PlaynCoreCanvas>) nil_chk([((id<PlaynCoreCanvasImage>) nil_chk(image)) canvas])) setStrokeColorWithInt:[TripleplayUtilColors BLACK]];
  float ratio = 1.3f;
  float w = width - padding * 2;
  float h = w / ratio;
  float y = height - h / 2 - padding;
  float x = width / 2;
  for (int i = 0; i < 3; i++) {
    (void) [((id<PlaynCoreCanvas>) nil_chk([((id<PlaynCoreCanvasImage>) nil_chk(image)) canvas])) fillRoundRectWithFloat:x - w / 2 withFloat:y - h / 2 withFloat:w withFloat:h withFloat:rad];
    (void) [((id<PlaynCoreCanvas>) nil_chk([((id<PlaynCoreCanvasImage>) nil_chk(image)) canvas])) strokeRoundRectWithFloat:x - w / 2 + 0.5f withFloat:y - h / 2 + 0.5f withFloat:w - 1 withFloat:h - 1 withFloat:rad];
    y -= h / 2;
    w -= cellSize / 5;
    h = w / ratio;
  }
  return image;
}

- (id)init {
  if ((self = [super init])) {
    projectileStart__ = [[PythagorasFVector alloc] init];
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TuxkidsTuxblocksCoreDefenseTowerZapper *typedCopy = (TuxkidsTuxblocksCoreDefenseTowerZapper *) copy;
  typedCopy.projectileStart_ = projectileStart__;
}

@end
