//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/playn/showcase/core/sprites/Pea.java
//
//  Created by Thomas on 7/15/13.
//

#import "java/lang/Math.h"
#import "java/lang/Throwable.h"
#import "playn/core/GroupLayer.h"
#import "playn/core/ImageLayer.h"
#import "playn/core/Layer.h"
#import "playn/core/Log.h"
#import "playn/core/PlayN.h"
#import "playn/showcase/core/sprites/Pea.h"
#import "playn/showcase/core/sprites/Sprite.h"
#import "playn/showcase/core/sprites/SpriteLoader.h"

@implementation PlaynShowcaseCoreSpritesPea

static NSString * PlaynShowcaseCoreSpritesPea_IMAGE_;
static NSString * PlaynShowcaseCoreSpritesPea_JSON_;
static NSString * PlaynShowcaseCoreSpritesPea_JSON_WITH_IMAGE_;

@synthesize sprite = sprite_;
@synthesize spriteIndex = spriteIndex_;
@synthesize angle = angle_;
@synthesize hasLoaded = hasLoaded_;

+ (NSString *)IMAGE {
  return PlaynShowcaseCoreSpritesPea_IMAGE_;
}

+ (void)setIMAGE:(NSString *)IMAGE {
  PlaynShowcaseCoreSpritesPea_IMAGE_ = IMAGE;
}

+ (NSString *)JSON {
  return PlaynShowcaseCoreSpritesPea_JSON_;
}

+ (void)setJSON:(NSString *)JSON {
  PlaynShowcaseCoreSpritesPea_JSON_ = JSON;
}

+ (NSString *)JSON_WITH_IMAGE {
  return PlaynShowcaseCoreSpritesPea_JSON_WITH_IMAGE_;
}

+ (void)setJSON_WITH_IMAGE:(NSString *)JSON_WITH_IMAGE {
  PlaynShowcaseCoreSpritesPea_JSON_WITH_IMAGE_ = JSON_WITH_IMAGE;
}

- (id)initWithPlaynCoreGroupLayer:(id<PlaynCoreGroupLayer>)peaLayer
                        withFloat:(float)x
                        withFloat:(float)y {
  if ((self = [super init])) {
    spriteIndex_ = 0;
    hasLoaded_ = NO;
    sprite_ = [PlaynShowcaseCoreSpritesSpriteLoader getSpriteWithNSString:PlaynShowcaseCoreSpritesPea_IMAGE_ withNSString:PlaynShowcaseCoreSpritesPea_JSON_];
    [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite_)) addCallbackWithPlaynCoreUtilCallback:[[PlaynShowcaseCoreSpritesPea_$1 alloc] initWithPlaynShowcaseCoreSpritesPea:self withFloat:x withFloat:y withPlaynCoreGroupLayer:peaLayer]];
  }
  return self;
}

- (void)updateWithInt:(int)delta {
  if (hasLoaded_) {
    if ([JavaLangMath random] > 0.95) {
      spriteIndex_ = (spriteIndex_ + 1) % [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite_)) numSprites];
      [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite_)) setSpriteWithInt:spriteIndex_];
    }
    angle_ += delta;
    (void) [((id<PlaynCoreImageLayer>) [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite_)) layer]) setRotationWithFloat:angle_];
  }
}

+ (void)initialize {
  if (self == [PlaynShowcaseCoreSpritesPea class]) {
    PlaynShowcaseCoreSpritesPea_IMAGE_ = @"sprites/peasprites.png";
    PlaynShowcaseCoreSpritesPea_JSON_ = @"sprites/peasprite.json";
    PlaynShowcaseCoreSpritesPea_JSON_WITH_IMAGE_ = @"sprites/peasprite2.json";
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynShowcaseCoreSpritesPea *typedCopy = (PlaynShowcaseCoreSpritesPea *) copy;
  typedCopy.sprite = sprite_;
  typedCopy.spriteIndex = spriteIndex_;
  typedCopy.angle = angle_;
  typedCopy.hasLoaded = hasLoaded_;
}

@end
@implementation PlaynShowcaseCoreSpritesPea_$1

@synthesize this$0 = this$0_;
@synthesize val$x = val$x_;
@synthesize val$y = val$y_;
@synthesize val$peaLayer = val$peaLayer_;

- (void)onSuccessWithId:(PlaynShowcaseCoreSpritesSprite *)sprite {
  [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) setSpriteWithInt:this$0_.spriteIndex];
  (void) [((id<PlaynCoreImageLayer>) [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) layer]) setOriginWithFloat:[((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) width] / 2.0f withFloat:[((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) height] / 2.0f];
  (void) [((id<PlaynCoreImageLayer>) [((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) layer]) setTranslationWithFloat:val$x_ withFloat:val$y_];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(val$peaLayer_)) addWithPlaynCoreLayer:[((PlaynShowcaseCoreSpritesSprite *) NIL_CHK(sprite)) layer]];
  this$0_.hasLoaded = YES;
}

- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)err {
  [((id<PlaynCoreLog>) [PlaynCorePlayN log]) errorWithNSString:@"Error loading image!" withJavaLangThrowable:err];
}

- (id)initWithPlaynShowcaseCoreSpritesPea:(PlaynShowcaseCoreSpritesPea *)outer$
                                withFloat:(float)capture$0
                                withFloat:(float)capture$1
                  withPlaynCoreGroupLayer:(id<PlaynCoreGroupLayer>)capture$2 {
  if ((self = [super init])) {
    this$0_ = outer$;
    val$x_ = capture$0;
    val$y_ = capture$1;
    val$peaLayer_ = capture$2;
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynShowcaseCoreSpritesPea_$1 *typedCopy = (PlaynShowcaseCoreSpritesPea_$1 *) copy;
  typedCopy.this$0 = this$0_;
  typedCopy.val$x = val$x_;
  typedCopy.val$y = val$y_;
  typedCopy.val$peaLayer = val$peaLayer_;
}

@end
