//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/playn/showcase/core/sprites/SpritesDemo.java
//
//  Created by Thomas on 7/15/13.
//

@protocol JavaUtilList;
@protocol PlaynCoreGroupLayer;
@protocol PlaynCorePointer_Event;
@protocol PlaynCoreSound;

#import "JreEmulation.h"
#import "playn/core/Pointer.h"
#import "playn/showcase/core/Demo.h"

@interface PlaynShowcaseCoreSpritesSpritesDemo : PlaynShowcaseCoreDemo {
 @public
  id<PlaynCoreGroupLayer> layer_;
  id<JavaUtilList> peas_;
  id<PlaynCoreSound> ding_;
}

@property (nonatomic, strong) id<PlaynCoreGroupLayer> layer;
@property (nonatomic, strong) id<JavaUtilList> peas;
@property (nonatomic, strong) id<PlaynCoreSound> ding;

- (NSString *)name;
- (void)init__ OBJC_METHOD_FAMILY_NONE;
- (void)addPeaWithFloat:(float)x
              withFloat:(float)y;
- (void)shutdown;
- (void)paintWithFloat:(float)alpha;
- (void)updateWithInt:(int)delta;
- (id)init;
@end

@interface PlaynShowcaseCoreSpritesSpritesDemo_$1 : PlaynCorePointer_Adapter {
 @public
  PlaynShowcaseCoreSpritesSpritesDemo *this$0_;
}

@property (nonatomic, strong) PlaynShowcaseCoreSpritesSpritesDemo *this$0;

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (id)initWithPlaynShowcaseCoreSpritesSpritesDemo:(PlaynShowcaseCoreSpritesSpritesDemo *)outer$;
@end
