//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/MalformedParameterizedTypeException.java
//
//  Created by tball on 6/22/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaLangReflectMalformedParameterizedTypeException_serialVersionUID -5696557788586220964

@interface JavaLangReflectMalformedParameterizedTypeException : JavaLangRuntimeException {
}

- (id)init;
@end
