//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/defense/DiscreteGridObject.java
//
//  Created by Thomas on 7/25/13.
//

#ifndef _TuxkidsTuxblocksCoreDefenseDiscreteGridObject_H_
#define _TuxkidsTuxblocksCoreDefenseDiscreteGridObject_H_

@class PythagorasIPoint;
@class TuxkidsTuxblocksCoreDefenseGrid;

#import "JreEmulation.h"
#include "tuxkids/tuxblocks/core/defense/GridObject.h"

@interface TuxkidsTuxblocksCoreDefenseDiscreteGridObject : TuxkidsTuxblocksCoreDefenseGridObject {
 @public
  PythagorasIPoint *coordinates__;
  float baseDepth_;
}

@property (nonatomic, strong) PythagorasIPoint *coordinates_;
@property (nonatomic, assign) float baseDepth;

- (PythagorasIPoint *)coordinates;
- (float)depthRow;
- (float)depthCol;
- (void)updateDepth;
- (BOOL)updateWithInt:(int)delta;
- (void)placeWithTuxkidsTuxblocksCoreDefenseGrid:(TuxkidsTuxblocksCoreDefenseGrid *)grid
                                       withFloat:(float)baseDepth;
- (void)setDepthWithFloat:(float)depth;
- (id)init;
@end

#endif // _TuxkidsTuxblocksCoreDefenseDiscreteGridObject_H_
