//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/defense/Pathing.java
//
//  Created by Thomas on 7/25/13.
//

#ifndef _TuxkidsTuxblocksCoreDefensePathing_H_
#define _TuxkidsTuxblocksCoreDefensePathing_H_

@class IOSIntArray;
@class JavaUtilHashMap;
@class PythagorasIPoint;
@class TuxkidsTuxblocksCoreDefenseGrid;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/util/Comparator.h"

@interface TuxkidsTuxblocksCoreDefensePathing : NSObject {
}

+ (IOSIntArray *)offRows;
+ (IOSIntArray *)offCols;
+ (id<JavaUtilList>)getPathWithTuxkidsTuxblocksCoreDefenseGrid:(TuxkidsTuxblocksCoreDefenseGrid *)grid
                                          withPythagorasIPoint:(PythagorasIPoint *)from
                                          withPythagorasIPoint:(PythagorasIPoint *)to;
+ (id<JavaUtilList>)reconstructPathWithJavaUtilHashMap:(JavaUtilHashMap *)cameFrom
                                  withPythagorasIPoint:(PythagorasIPoint *)currentNode;
- (id)init;
@end

@interface TuxkidsTuxblocksCoreDefensePathing_$1 : NSObject < JavaUtilComparator > {
 @public
  JavaUtilHashMap *val$fScore_;
}

@property (nonatomic, strong) JavaUtilHashMap *val$fScore;

- (int)compareWithId:(PythagorasIPoint *)o1
              withId:(PythagorasIPoint *)o2;
- (id)initWithJavaUtilHashMap:(JavaUtilHashMap *)capture$0;
@end

#endif // _TuxkidsTuxblocksCoreDefensePathing_H_
