//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/EntityResolver.java
//
//  Created by tball on 6/22/13.
//

@class OrgXmlSaxInputSource;

#import "JreEmulation.h"

@protocol OrgXmlSaxEntityResolver < NSObject >
- (OrgXmlSaxInputSource *)resolveEntityWithNSString:(NSString *)publicId
                                       withNSString:(NSString *)systemId;
@end
