//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/FileOutputStream.java
//
//  Created by tball on 6/22/13.
//

@class IOSByteArray;
@class JavaIoFile;
@class JavaIoFileDescriptor;

#import "JreEmulation.h"
#import "java/io/Closeable.h"
#import "java/io/OutputStream.h"

@interface JavaIoFileOutputStream : JavaIoOutputStream < JavaIoCloseable > {
 @public
  JavaIoFileDescriptor *fd_;
}

@property (nonatomic, retain) JavaIoFileDescriptor *fd;

- (id)initWithJavaIoFile:(JavaIoFile *)file;
- (id)initWithJavaIoFile:(JavaIoFile *)file
                withBOOL:(BOOL)append;
- (long long int)openWithNSString:(NSString *)path
                         withBOOL:(BOOL)append;
- (id)initWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;
- (id)initWithNSString:(NSString *)filename;
- (id)initWithNSString:(NSString *)filename
              withBOOL:(BOOL)append;
- (void)close;
- (void)closeWithLongInt:(long long int)descriptor;
- (void)dealloc;
- (JavaIoFileDescriptor *)getFD;
- (void)writeWithJavaLangByteArray:(IOSByteArray *)buffer;
- (void)writeWithJavaLangByteArray:(IOSByteArray *)buffer
                           withInt:(int)offset
                           withInt:(int)count;
- (int)nativeWriteWithJavaLangByteArray:(IOSByteArray *)buffer
                                withInt:(int)offset
                                withInt:(int)count;
- (void)writeWithInt:(int)oneByte;
- (void)openCheck;
@end
