//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/PrintWriter.java
//
//  Created by tball on 6/22/13.
//

@class IOSCharArray;
@class JavaIoFile;
@class JavaIoOutputStream;
@protocol JavaLangCharSequence;

#import "JreEmulation.h"
#import "java/io/Writer.h"

@interface JavaIoPrintWriter : JavaIoWriter {
 @public
  JavaIoWriter *out_;
  BOOL ioError_;
  BOOL autoflush_;
  NSString *lineSeparator_;
}

@property (nonatomic, retain) JavaIoWriter *out;
@property (nonatomic, assign) BOOL ioError;
@property (nonatomic, assign) BOOL autoflush;
@property (nonatomic, copy) NSString *lineSeparator;

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                        withBOOL:(BOOL)autoflush;
- (id)initWithJavaIoWriter:(JavaIoWriter *)wr;
- (id)initWithJavaIoWriter:(JavaIoWriter *)wr
                  withBOOL:(BOOL)autoflush;
- (id)initWithJavaIoFile:(JavaIoFile *)file;
- (id)initWithJavaIoFile:(JavaIoFile *)file
            withNSString:(NSString *)csn;
- (id)initWithNSString:(NSString *)fileName;
- (BOOL)checkError;
- (void)close;
- (void)flush;
- (void)printWithJavaLangCharacterArray:(IOSCharArray *)charArray;
- (void)printWithUnichar:(unichar)ch;
- (void)printWithDouble:(double)dnum;
- (void)printWithFloat:(float)fnum;
- (void)printWithInt:(int)inum;
- (void)printWithLongInt:(long long int)lnum;
- (void)printWithId:(id)obj;
- (void)printWithNSString:(NSString *)str;
- (void)printWithBOOL:(BOOL)bool_;
- (void)println;
- (void)printlnWithJavaLangCharacterArray:(IOSCharArray *)charArray;
- (void)printlnWithUnichar:(unichar)ch;
- (void)printlnWithDouble:(double)dnum;
- (void)printlnWithFloat:(float)fnum;
- (void)printlnWithInt:(int)inum;
- (void)printlnWithLongInt:(long long int)lnum;
- (void)printlnWithId:(id)obj;
- (void)printlnWithNSString:(NSString *)str;
- (void)printlnWithBOOL:(BOOL)bool_;
- (void)setError;
- (void)writeWithJavaLangCharacterArray:(IOSCharArray *)buf;
- (void)writeWithJavaLangCharacterArray:(IOSCharArray *)buf
                                withInt:(int)offset
                                withInt:(int)count;
- (void)writeWithInt:(int)oneChar;
- (void)doWriteWithJavaLangCharacterArray:(IOSCharArray *)buf
                                  withInt:(int)offset
                                  withInt:(int)count;
- (void)writeWithNSString:(NSString *)str;
- (void)writeWithNSString:(NSString *)str
                  withInt:(int)offset
                  withInt:(int)count;
- (JavaIoPrintWriter *)appendWithUnichar:(unichar)c;
- (JavaIoPrintWriter *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq;
- (JavaIoPrintWriter *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq
                                              withInt:(int)start
                                              withInt:(int)end;
@end
