//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/PushbackReader.java
//
//  Created by tball on 6/22/13.
//

@class IOSCharArray;
@class JavaIoReader;

#import "JreEmulation.h"
#import "java/io/FilterReader.h"

@interface JavaIoPushbackReader : JavaIoFilterReader {
 @public
  IOSCharArray *buf_;
  int pos_;
}

@property (nonatomic, retain) IOSCharArray *buf;
@property (nonatomic, assign) int pos;

- (id)initWithJavaIoReader:(JavaIoReader *)inArg;
- (id)initWithJavaIoReader:(JavaIoReader *)inArg
                   withInt:(int)size;
- (void)close;
- (void)markWithInt:(int)readAheadLimit;
- (BOOL)markSupported;
- (int)read;
- (int)readWithJavaLangCharacterArray:(IOSCharArray *)buffer
                              withInt:(int)offset
                              withInt:(int)count;
- (BOOL)ready;
- (void)reset;
- (void)unreadWithJavaLangCharacterArray:(IOSCharArray *)buffer;
- (void)unreadWithJavaLangCharacterArray:(IOSCharArray *)buffer
                                 withInt:(int)offset
                                 withInt:(int)length;
- (void)unreadWithInt:(int)oneChar;
- (long long int)skipWithLongInt:(long long int)count;
@end
