//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/init/Lifespan.java
//
//  Created by Thomas on 7/10/13.
//

@class IOSFloatArray;
@class TripleplayUtilRandoms;

#import "JreEmulation.h"
#import "tripleplay/particle/Initializer.h"

@interface TripleplayParticleInitLifespan : NSObject {
}

+ (TripleplayParticleInitializer *)constantWithFloat:(float)lifespan;
+ (TripleplayParticleInitializer *)randomWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)rando
                                                         withFloat:(float)min
                                                         withFloat:(float)max;
- (id)init;
@end

@interface TripleplayParticleInitLifespan_$1 : TripleplayParticleInitializer {
 @public
  float val$lifespan_;
}

@property (nonatomic, assign) float val$lifespan;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE;
- (id)initWithFloat:(float)capture$0;
@end

@interface TripleplayParticleInitLifespan_$2 : TripleplayParticleInitializer {
 @public
  TripleplayUtilRandoms *val$rando_;
  float val$min_;
  float val$max_;
}

@property (nonatomic, strong) TripleplayUtilRandoms *val$rando;
@property (nonatomic, assign) float val$min;
@property (nonatomic, assign) float val$max;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE;
- (id)initWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)capture$0
                          withFloat:(float)capture$1
                          withFloat:(float)capture$2;
@end
