//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/NegativeArraySizeException.java
//
//  Created by tball on 6/22/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaLangNegativeArraySizeException_serialVersionUID -8960118058596991861

@interface JavaLangNegativeArraySizeException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
