//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/Plane.java
//
//  Created by Thomas on 7/25/13.
//

#include "IOSFloatArray.h"
#include "java/lang/Float.h"
#include "java/lang/Math.h"
#include "java/nio/FloatBuffer.h"
#include "pythagoras/f/IRay3.h"
#include "pythagoras/f/IVector3.h"
#include "pythagoras/f/MathUtil.h"
#include "pythagoras/f/Plane.h"
#include "pythagoras/f/Vector3.h"
#include "pythagoras/util/Platform.h"

@implementation PythagorasFPlane

static PythagorasFPlane * PythagorasFPlane_XY_PLANE_;
static PythagorasFPlane * PythagorasFPlane_XZ_PLANE_;
static PythagorasFPlane * PythagorasFPlane_YZ_PLANE_;

@synthesize constant_ = constant__;
@synthesize _normal = _normal_;
@synthesize _v1 = _v1_;
@synthesize _v2 = _v2_;

+ (PythagorasFPlane *)XY_PLANE {
  return PythagorasFPlane_XY_PLANE_;
}

+ (PythagorasFPlane *)XZ_PLANE {
  return PythagorasFPlane_XZ_PLANE_;
}

+ (PythagorasFPlane *)YZ_PLANE {
  return PythagorasFPlane_YZ_PLANE_;
}

- (id)initWithPythagorasFIVector3:(id<PythagorasFIVector3>)normal
                        withFloat:(float)constant {
  if ((self = [super init])) {
    _normal_ = [[PythagorasFVector3 alloc] init];
    _v1_ = [[PythagorasFVector3 alloc] init];
    _v2_ = [[PythagorasFVector3 alloc] init];
    (void) [self setWithPythagorasFIVector3:normal withFloat:constant];
  }
  return self;
}

- (id)initWithFloatArray:(IOSFloatArray *)values {
  if ((self = [super init])) {
    _normal_ = [[PythagorasFVector3 alloc] init];
    _v1_ = [[PythagorasFVector3 alloc] init];
    _v2_ = [[PythagorasFVector3 alloc] init];
    (void) [self setWithFloatArray:values];
  }
  return self;
}

- (id)initWithFloat:(float)a
          withFloat:(float)b
          withFloat:(float)c
          withFloat:(float)d {
  if ((self = [super init])) {
    _normal_ = [[PythagorasFVector3 alloc] init];
    _v1_ = [[PythagorasFVector3 alloc] init];
    _v2_ = [[PythagorasFVector3 alloc] init];
    (void) [self setWithFloat:a withFloat:b withFloat:c withFloat:d];
  }
  return self;
}

- (id)initWithPythagorasFPlane:(PythagorasFPlane *)other {
  if ((self = [super init])) {
    _normal_ = [[PythagorasFVector3 alloc] init];
    _v1_ = [[PythagorasFVector3 alloc] init];
    _v2_ = [[PythagorasFVector3 alloc] init];
    (void) [self setWithPythagorasFPlane:other];
  }
  return self;
}

- (id)init {
  if ((self = [super init])) {
    _normal_ = [[PythagorasFVector3 alloc] init];
    _v1_ = [[PythagorasFVector3 alloc] init];
    _v2_ = [[PythagorasFVector3 alloc] init];
  }
  return self;
}

- (PythagorasFPlane *)setWithPythagorasFPlane:(PythagorasFPlane *)other {
  return [self setWithPythagorasFIVector3:[((PythagorasFPlane *) nil_chk(other)) normal] withFloat:((PythagorasFPlane *) nil_chk(other)).constant_];
}

- (PythagorasFPlane *)setWithPythagorasFIVector3:(id<PythagorasFIVector3>)normal
                                       withFloat:(float)constant {
  return [self setWithFloat:[((id<PythagorasFIVector3>) nil_chk(normal)) x] withFloat:[((id<PythagorasFIVector3>) nil_chk(normal)) y] withFloat:[((id<PythagorasFIVector3>) nil_chk(normal)) z] withFloat:constant];
}

- (PythagorasFPlane *)setWithFloatArray:(IOSFloatArray *)values {
  return [self setWithFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:0] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:1] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:2] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:3]];
}

- (PythagorasFPlane *)setWithFloat:(float)a
                         withFloat:(float)b
                         withFloat:(float)c
                         withFloat:(float)d {
  (void) [((PythagorasFVector3 *) nil_chk(_normal_)) setWithFloat:a withFloat:b withFloat:c];
  constant__ = d;
  return self;
}

- (PythagorasFPlane *)fromPointsWithPythagorasFIVector3:(id<PythagorasFIVector3>)p1
                                withPythagorasFIVector3:(id<PythagorasFIVector3>)p2
                                withPythagorasFIVector3:(id<PythagorasFIVector3>)p3 {
  (void) [((id<PythagorasFIVector3>) nil_chk(p2)) subtractWithPythagorasFIVector3:p1 withPythagorasFVector3:_v1_];
  (void) [((id<PythagorasFIVector3>) nil_chk(p3)) subtractWithPythagorasFIVector3:p1 withPythagorasFVector3:_v2_];
  (void) [((PythagorasFVector3 *) nil_chk([((PythagorasFVector3 *) nil_chk(_v1_)) crossWithPythagorasFIVector3:_v2_ withPythagorasFVector3:_normal_])) normalizeLocal];
  constant__ = -[((PythagorasFVector3 *) nil_chk(_normal_)) dotWithPythagorasFIVector3:p1];
  return self;
}

- (PythagorasFPlane *)fromPointNormalWithPythagorasFIVector3:(id<PythagorasFIVector3>)pt
                                     withPythagorasFIVector3:(id<PythagorasFIVector3>)normal {
  return [self setWithPythagorasFIVector3:normal withFloat:-[((id<PythagorasFIVector3>) nil_chk(normal)) dotWithPythagorasFIVector3:pt]];
}

- (PythagorasFPlane *)negateLocal {
  return [self negateWithPythagorasFPlane:self];
}

- (float)constant {
  return constant__;
}

- (id<PythagorasFIVector3>)normal {
  return _normal_;
}

- (JavaNioFloatBuffer *)getWithJavaNioFloatBuffer:(JavaNioFloatBuffer *)buf {
  return [((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk(buf)) putWithFloat:((PythagorasFVector3 *) nil_chk(_normal_)).x_])) putWithFloat:((PythagorasFVector3 *) nil_chk(_normal_)).y_])) putWithFloat:((PythagorasFVector3 *) nil_chk(_normal_)).z_])) putWithFloat:constant__];
}

- (float)distanceWithPythagorasFIVector3:(id<PythagorasFIVector3>)pt {
  return [((PythagorasFVector3 *) nil_chk(_normal_)) dotWithPythagorasFIVector3:pt] + constant__;
}

- (PythagorasFPlane *)negate {
  return [self negateWithPythagorasFPlane:[[PythagorasFPlane alloc] init]];
}

- (PythagorasFPlane *)negateWithPythagorasFPlane:(PythagorasFPlane *)result {
  (void) [((PythagorasFVector3 *) nil_chk(_normal_)) negateWithPythagorasFVector3:((PythagorasFPlane *) nil_chk(result))._normal];
  ((PythagorasFPlane *) nil_chk(result)).constant_ = -constant__;
  return result;
}

- (BOOL)intersectionWithPythagorasFIRay3:(id<PythagorasFIRay3>)ray
                  withPythagorasFVector3:(PythagorasFVector3 *)result {
  float distance = [self distanceWithPythagorasFIRay3:ray];
  if ([JavaLangFloat isNaNWithFloat:distance] || distance < 0.0f) {
    return NO;
  }
  else {
    (void) [((id<PythagorasFIVector3>) nil_chk([((id<PythagorasFIRay3>) nil_chk(ray)) origin])) addScaledWithPythagorasFIVector3:[((id<PythagorasFIRay3>) nil_chk(ray)) direction] withFloat:distance withPythagorasFVector3:result];
    return YES;
  }
}

- (float)distanceWithPythagorasFIRay3:(id<PythagorasFIRay3>)ray {
  float dividend = -[self distanceWithPythagorasFIVector3:[((id<PythagorasFIRay3>) nil_chk(ray)) origin]];
  float divisor = [((PythagorasFVector3 *) nil_chk(_normal_)) dotWithPythagorasFIVector3:[((id<PythagorasFIRay3>) nil_chk(ray)) direction]];
  if ([JavaLangMath absWithFloat:dividend] < PythagorasFMathUtil_EPSILON) {
    return 0.0f;
  }
  else if ([JavaLangMath absWithFloat:divisor] < PythagorasFMathUtil_EPSILON) {
    return JavaLangFloat_NaN;
  }
  else {
    return dividend / divisor;
  }
}

- (NSUInteger)hash {
  return [((PythagorasFVector3 *) nil_chk(_normal_)) hash] ^ [PythagorasUtilPlatform hashCodeWithFloat:constant__];
}

- (BOOL)isEqual:(id)other {
  if (!([other isKindOfClass:[PythagorasFPlane class]])) {
    return NO;
  }
  PythagorasFPlane *oplane = (PythagorasFPlane *) other;
  return constant__ == ((PythagorasFPlane *) nil_chk(oplane)).constant_ && [((PythagorasFVector3 *) nil_chk(_normal_)) isEqual:[((PythagorasFPlane *) nil_chk(oplane)) normal]];
}

+ (void)initialize {
  if (self == [PythagorasFPlane class]) {
    PythagorasFPlane_XY_PLANE_ = [[PythagorasFPlane alloc] initWithPythagorasFIVector3:[PythagorasFVector3 UNIT_Z] withFloat:0.0f];
    PythagorasFPlane_XZ_PLANE_ = [[PythagorasFPlane alloc] initWithPythagorasFIVector3:[PythagorasFVector3 UNIT_Y] withFloat:0.0f];
    PythagorasFPlane_YZ_PLANE_ = [[PythagorasFPlane alloc] initWithPythagorasFIVector3:[PythagorasFVector3 UNIT_X] withFloat:0.0f];
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PythagorasFPlane *typedCopy = (PythagorasFPlane *) copy;
  typedCopy.constant_ = constant__;
  typedCopy._normal = _normal_;
  typedCopy._v1 = _v1_;
  typedCopy._v2 = _v2_;
}

@end
