//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/Vector3.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasFVector3_RESTRICT
#define PythagorasFVector3_INCLUDE_ALL 1
#endif
#undef PythagorasFVector3_RESTRICT

#if !defined (_PythagorasFVector3_) && (PythagorasFVector3_INCLUDE_ALL || PythagorasFVector3_INCLUDE)
#define _PythagorasFVector3_

@class IOSFloatArray;
@class JavaNioFloatBuffer;

#define PythagorasFIVector3_RESTRICT 1
#define PythagorasFIVector3_INCLUDE 1
#include "pythagoras/f/IVector3.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@interface PythagorasFVector3 : NSObject < PythagorasFIVector3, JavaIoSerializable > {
 @public
  float x__, y__, z__;
}

@property (nonatomic, assign) float x_;
@property (nonatomic, assign) float y_;
@property (nonatomic, assign) float z_;

+ (id<PythagorasFIVector3>)UNIT_X;
+ (id<PythagorasFIVector3>)UNIT_Y;
+ (id<PythagorasFIVector3>)UNIT_Z;
+ (id<PythagorasFIVector3>)UNIT_XYZ;
+ (id<PythagorasFIVector3>)NORMAL_XYZ;
+ (id<PythagorasFIVector3>)ZERO;
+ (id<PythagorasFIVector3>)MIN_VALUE;
+ (id<PythagorasFIVector3>)MAX_VALUE;
- (id)initWithFloat:(float)x
          withFloat:(float)y
          withFloat:(float)z;
- (id)initWithFloatArray:(IOSFloatArray *)values;
- (id)initWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (id)init;
- (PythagorasFVector3 *)crossLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)negateLocal;
- (PythagorasFVector3 *)absLocal;
- (PythagorasFVector3 *)normalizeLocal;
- (PythagorasFVector3 *)multLocalWithFloat:(float)v;
- (PythagorasFVector3 *)multLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)addLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)subtractLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)addLocalWithFloat:(float)x
                                withFloat:(float)y
                                withFloat:(float)z;
- (PythagorasFVector3 *)addScaledLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                                    withFloat:(float)v;
- (PythagorasFVector3 *)lerpLocalWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                               withFloat:(float)t;
- (PythagorasFVector3 *)setWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)setWithFloatArray:(IOSFloatArray *)values;
- (PythagorasFVector3 *)setWithFloat:(float)x
                           withFloat:(float)y
                           withFloat:(float)z;
- (float)x;
- (float)y;
- (float)z;
- (float)dotWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)crossWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)crossWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                              withPythagorasFVector3:(PythagorasFVector3 *)result;
- (float)tripleWithPythagorasFIVector3:(id<PythagorasFIVector3>)b
               withPythagorasFIVector3:(id<PythagorasFIVector3>)c;
- (PythagorasFVector3 *)negate;
- (PythagorasFVector3 *)negateWithPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)abs;
- (PythagorasFVector3 *)absWithPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)normalize;
- (PythagorasFVector3 *)normalizeWithPythagorasFVector3:(PythagorasFVector3 *)result;
- (float)angleWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (float)length;
- (float)lengthSquared;
- (float)distanceWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (float)distanceSquaredWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (float)manhattanDistanceWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)multWithFloat:(float)v;
- (PythagorasFVector3 *)multWithFloat:(float)v
               withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)multWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)multWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                             withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)addWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)addWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                            withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)subtractWithPythagorasFIVector3:(id<PythagorasFIVector3>)other;
- (PythagorasFVector3 *)subtractWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                 withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)addWithFloat:(float)x
                           withFloat:(float)y
                           withFloat:(float)z;
- (PythagorasFVector3 *)addWithFloat:(float)x
                           withFloat:(float)y
                           withFloat:(float)z
              withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)addScaledWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                               withFloat:(float)v;
- (PythagorasFVector3 *)addScaledWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                               withFloat:(float)v
                                  withPythagorasFVector3:(PythagorasFVector3 *)result;
- (PythagorasFVector3 *)lerpWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                          withFloat:(float)t;
- (PythagorasFVector3 *)lerpWithPythagorasFIVector3:(id<PythagorasFIVector3>)other
                                          withFloat:(float)t
                             withPythagorasFVector3:(PythagorasFVector3 *)result;
- (float)getWithInt:(int)idx;
- (void)getWithFloatArray:(IOSFloatArray *)values;
- (JavaNioFloatBuffer *)getWithJavaNioFloatBuffer:(JavaNioFloatBuffer *)buf;
- (NSString *)description;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)other;
@end
#endif
