//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/Vector4.java
//
//  Created by Thomas on 7/25/13.
//

#include "IOSFloatArray.h"
#include "java/lang/Math.h"
#include "java/nio/FloatBuffer.h"
#include "pythagoras/f/IMatrix4.h"
#include "pythagoras/f/IVector4.h"
#include "pythagoras/f/Vector4.h"
#include "pythagoras/util/Platform.h"

@implementation PythagorasFVector4

@synthesize x_ = x__;
@synthesize y_ = y__;
@synthesize z_ = z__;
@synthesize w_ = w__;

- (id)initWithFloat:(float)x
          withFloat:(float)y
          withFloat:(float)z
          withFloat:(float)w {
  if ((self = [super init])) {
    (void) [self setWithFloat:x withFloat:y withFloat:z withFloat:w];
  }
  return self;
}

- (id)initWithFloatArray:(IOSFloatArray *)values {
  if ((self = [super init])) {
    (void) [self setWithFloatArray:values];
  }
  return self;
}

- (id)initWithJavaNioFloatBuffer:(JavaNioFloatBuffer *)buf {
  if ((self = [super init])) {
    (void) [self setWithJavaNioFloatBuffer:buf];
  }
  return self;
}

- (id)initWithPythagorasFIVector4:(id<PythagorasFIVector4>)other {
  if ((self = [super init])) {
    (void) [self setWithPythagorasFIVector4:other];
  }
  return self;
}

- (id)init {
  return [super init];
}

- (PythagorasFVector4 *)setWithPythagorasFIVector4:(id<PythagorasFIVector4>)other {
  return [self setWithFloat:[((id<PythagorasFIVector4>) nil_chk(other)) x] withFloat:[((id<PythagorasFIVector4>) nil_chk(other)) y] withFloat:[((id<PythagorasFIVector4>) nil_chk(other)) z] withFloat:[((id<PythagorasFIVector4>) nil_chk(other)) w]];
}

- (PythagorasFVector4 *)setWithFloatArray:(IOSFloatArray *)values {
  return [self setWithFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:0] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:1] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:2] withFloat:[((IOSFloatArray *) nil_chk(values)) floatAtIndex:3]];
}

- (PythagorasFVector4 *)setWithJavaNioFloatBuffer:(JavaNioFloatBuffer *)buf {
  return [self setWithFloat:[((JavaNioFloatBuffer *) nil_chk(buf)) get] withFloat:[((JavaNioFloatBuffer *) nil_chk(buf)) get] withFloat:[((JavaNioFloatBuffer *) nil_chk(buf)) get] withFloat:[((JavaNioFloatBuffer *) nil_chk(buf)) get]];
}

- (PythagorasFVector4 *)setWithFloat:(float)x
                           withFloat:(float)y
                           withFloat:(float)z
                           withFloat:(float)w {
  self.x_ = x;
  self.y_ = y;
  self.z_ = z;
  self.w_ = w;
  return self;
}

- (PythagorasFVector4 *)negateLocal {
  return [self negateWithPythagorasFVector4:self];
}

- (PythagorasFVector4 *)absLocal {
  return [self absWithPythagorasFVector4:self];
}

- (PythagorasFVector4 *)multLocalWithFloat:(float)v {
  return [self multWithFloat:v withPythagorasFVector4:self];
}

- (PythagorasFVector4 *)multLocalWithPythagorasFIMatrix4:(id<PythagorasFIMatrix4>)matrix {
  return [self multWithPythagorasFIMatrix4:matrix withPythagorasFVector4:self];
}

- (float)x {
  return x__;
}

- (float)y {
  return y__;
}

- (float)z {
  return z__;
}

- (float)w {
  return w__;
}

- (JavaNioFloatBuffer *)getWithJavaNioFloatBuffer:(JavaNioFloatBuffer *)buf {
  return [((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk([((JavaNioFloatBuffer *) nil_chk(buf)) putWithFloat:x__])) putWithFloat:y__])) putWithFloat:z__])) putWithFloat:w__];
}

- (BOOL)epsilonEqualsWithPythagorasFIVector4:(id<PythagorasFIVector4>)other
                                   withFloat:(float)epsilon {
  return ([JavaLangMath absWithFloat:x__ - [((id<PythagorasFIVector4>) nil_chk(other)) x]] < epsilon && [JavaLangMath absWithFloat:y__ - [((id<PythagorasFIVector4>) nil_chk(other)) y]] < epsilon && [JavaLangMath absWithFloat:z__ - [((id<PythagorasFIVector4>) nil_chk(other)) z]] < epsilon && [JavaLangMath absWithFloat:w__ - [((id<PythagorasFIVector4>) nil_chk(other)) w]] < epsilon);
}

- (PythagorasFVector4 *)negate {
  return [self negateWithPythagorasFVector4:[[PythagorasFVector4 alloc] init]];
}

- (PythagorasFVector4 *)negateWithPythagorasFVector4:(PythagorasFVector4 *)result {
  return [((PythagorasFVector4 *) nil_chk(result)) setWithFloat:-x__ withFloat:-y__ withFloat:-z__ withFloat:-w__];
}

- (PythagorasFVector4 *)abs {
  return [self absWithPythagorasFVector4:[[PythagorasFVector4 alloc] init]];
}

- (PythagorasFVector4 *)absWithPythagorasFVector4:(PythagorasFVector4 *)result {
  return [((PythagorasFVector4 *) nil_chk(result)) setWithFloat:[JavaLangMath absWithFloat:x__] withFloat:[JavaLangMath absWithFloat:y__] withFloat:[JavaLangMath absWithFloat:z__] withFloat:[JavaLangMath absWithFloat:w__]];
}

- (PythagorasFVector4 *)multWithFloat:(float)v {
  return [self multWithFloat:v withPythagorasFVector4:[[PythagorasFVector4 alloc] init]];
}

- (PythagorasFVector4 *)multWithFloat:(float)v
               withPythagorasFVector4:(PythagorasFVector4 *)result {
  return [((PythagorasFVector4 *) nil_chk(result)) setWithFloat:x__ * v withFloat:y__ * v withFloat:z__ * v withFloat:w__ * v];
}

- (PythagorasFVector4 *)multWithPythagorasFIMatrix4:(id<PythagorasFIMatrix4>)matrix {
  return [self multWithPythagorasFIMatrix4:matrix withPythagorasFVector4:[[PythagorasFVector4 alloc] init]];
}

- (PythagorasFVector4 *)multWithPythagorasFIMatrix4:(id<PythagorasFIMatrix4>)matrix
                             withPythagorasFVector4:(PythagorasFVector4 *)result {
  float m00 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m00], m10 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m10], m20 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m20], m30 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m30];
  float m01 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m01], m11 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m11], m21 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m21], m31 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m31];
  float m02 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m02], m12 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m12], m22 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m22], m32 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m32];
  float m03 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m03], m13 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m13], m23 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m23], m33 = [((id<PythagorasFIMatrix4>) nil_chk(matrix)) m33];
  float vx = x__, vy = y__, vz = z__, vw = w__;
  return [((PythagorasFVector4 *) nil_chk(result)) setWithFloat:m00 * vx + m01 * vy + m02 * vz + m03 * vw withFloat:m10 * vx + m11 * vy + m12 * vz + m13 * vw withFloat:m20 * vx + m21 * vy + m22 * vz + m23 * vw withFloat:m30 * vx + m31 * vy + m32 * vz + m33 * vw];
}

- (NSString *)description {
  return [NSString stringWithFormat:@"[%f, %f, %f, %f]", x__, y__, z__, w__];
}

- (NSUInteger)hash {
  return [PythagorasUtilPlatform hashCodeWithFloat:x__] ^ [PythagorasUtilPlatform hashCodeWithFloat:y__] ^ [PythagorasUtilPlatform hashCodeWithFloat:z__] ^ [PythagorasUtilPlatform hashCodeWithFloat:w__];
}

- (BOOL)isEqual:(id)other {
  if (!([other isKindOfClass:[PythagorasFVector4 class]])) {
    return NO;
  }
  PythagorasFVector4 *ovec = (PythagorasFVector4 *) other;
  return (x__ == ((PythagorasFVector4 *) nil_chk(ovec)).x_ && y__ == ((PythagorasFVector4 *) nil_chk(ovec)).y_ && z__ == ((PythagorasFVector4 *) nil_chk(ovec)).z_ && w__ == ((PythagorasFVector4 *) nil_chk(ovec)).w_);
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PythagorasFVector4 *typedCopy = (PythagorasFVector4 *) copy;
  typedCopy.x_ = x__;
  typedCopy.y_ = y__;
  typedCopy.z_ = z__;
  typedCopy.w_ = w__;
}

@end
