//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/playn/sample/cute/core/CuteGame.java
//
//  Created by Thomas on 7/25/13.
//

#ifndef _PlaynSampleCuteCoreCuteGame_H_
#define _PlaynSampleCuteCoreCuteGame_H_

@class IOSObjectArray;
@class JavaLangThrowable;
@class PlaynSampleCuteCoreCuteObject;
@class PlaynSampleCuteCoreCuteWorld;
@protocol JavaUtilMap;
@protocol PlaynCoreImmediateLayer;
@protocol PlaynCoreKeyboard_Event;
@protocol PlaynCoreKeyboard_TypedEvent;
@protocol PlaynCorePointer_Event;
@protocol PlaynCoreSurface;

#import "JreEmulation.h"
#include "playn/core/Game.h"
#include "playn/core/ImmediateLayer.h"
#include "playn/core/Keyboard.h"
#include "playn/core/Pointer.h"
#include "playn/core/util/Callback.h"

#define PlaynSampleCuteCoreCuteGame_NUM_STARS 10

@interface PlaynSampleCuteCoreCuteGame : PlaynCoreGame_Default < PlaynCoreKeyboard_Listener > {
 @public
  id<PlaynCoreImmediateLayer> gameLayer_;
  float frameAlpha_;
  PlaynSampleCuteCoreCuteWorld *world_;
  PlaynSampleCuteCoreCuteObject *catGirl_;
  IOSObjectArray *stars_;
  BOOL controlLeft_, controlRight_, controlUp_, controlDown_;
  BOOL controlJump_;
  float touchVectorX_, touchVectorY_;
}

@property (nonatomic, strong) id<PlaynCoreImmediateLayer> gameLayer;
@property (nonatomic, assign) float frameAlpha;
@property (nonatomic, strong) PlaynSampleCuteCoreCuteWorld *world;
@property (nonatomic, strong) PlaynSampleCuteCoreCuteObject *catGirl;
@property (nonatomic, strong) IOSObjectArray *stars;
@property (nonatomic, assign) BOOL controlLeft;
@property (nonatomic, assign) BOOL controlRight;
@property (nonatomic, assign) BOOL controlUp;
@property (nonatomic, assign) BOOL controlDown;
@property (nonatomic, assign) BOOL controlJump;
@property (nonatomic, assign) float touchVectorX;
@property (nonatomic, assign) float touchVectorY;

+ (id<JavaUtilMap>)ADD_TILE_KEYS;
+ (void)setADD_TILE_KEYS:(id<JavaUtilMap>)ADD_TILE_KEYS;
- (id)init;
- (void)init__ OBJC_METHOD_FAMILY_NONE;
- (void)initStuff OBJC_METHOD_FAMILY_NONE;
- (void)onKeyDownWithPlaynCoreKeyboard_Event:(id<PlaynCoreKeyboard_Event>)event;
- (void)onKeyTypedWithPlaynCoreKeyboard_TypedEvent:(id<PlaynCoreKeyboard_TypedEvent>)event;
- (void)onKeyUpWithPlaynCoreKeyboard_Event:(id<PlaynCoreKeyboard_Event>)event;
- (void)updateWithInt:(int)delta;
- (void)paintWithFloat:(float)alpha;
- (void)touchMoveWithFloat:(float)x
                 withFloat:(float)y;
- (void)addTileWithInt:(int)x
               withInt:(int)y
               withInt:(int)type;
- (void)removeTopTileWithInt:(int)x
                     withInt:(int)y;
- (void)postWithNSString:(NSString *)payload;
@end

@interface PlaynSampleCuteCoreCuteGame_$1 : NSObject < PlaynCorePointer_Listener > {
 @public
  PlaynSampleCuteCoreCuteGame *this$0_;
}

@property (nonatomic, strong) PlaynSampleCuteCoreCuteGame *this$0;

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (id)initWithPlaynSampleCuteCoreCuteGame:(PlaynSampleCuteCoreCuteGame *)outer$;
@end

@interface PlaynSampleCuteCoreCuteGame_$2 : NSObject < PlaynCoreImmediateLayer_Renderer > {
 @public
  PlaynSampleCuteCoreCuteGame *this$0_;
}

@property (nonatomic, strong) PlaynSampleCuteCoreCuteGame *this$0;

- (void)renderWithPlaynCoreSurface:(id<PlaynCoreSurface>)surface;
- (id)initWithPlaynSampleCuteCoreCuteGame:(PlaynSampleCuteCoreCuteGame *)outer$;
@end

@interface PlaynSampleCuteCoreCuteGame_$3 : NSObject < PlaynCoreUtilCallback > {
}

- (void)onSuccessWithId:(NSString *)response;
- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)error;
- (id)init;
@end

#endif // _PlaynSampleCuteCoreCuteGame_H_
