//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/AbstractTextLayout.java
//
//  Created by Thomas on 7/25/13.
//

#include "playn/core/AbstractTextLayout.h"
#include "playn/core/Graphics.h"
#include "playn/core/TextFormat.h"
#include "pythagoras/f/Rectangle.h"

@implementation PlaynCoreAbstractTextLayout

@synthesize format_ = format__;
@synthesize pad = pad_;
@synthesize width_ = width__;
@synthesize height_ = height__;

- (float)width {
  return width__ + 2 * pad_;
}

- (float)height {
  return height__ + 2 * pad_;
}

- (PlaynCoreTextFormat *)format {
  return format__;
}

- (id)initWithPlaynCoreGraphics:(id<PlaynCoreGraphics>)gfx
                   withNSString:(NSString *)text
        withPlaynCoreTextFormat:(PlaynCoreTextFormat *)format {
  if ((self = [super init])) {
    self.format_ = format;
    self.pad = 1 / [((id<PlaynCoreGraphics>) nil_chk(gfx)) scaleFactor];
  }
  return self;
}

- (float)ascent {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (float)descent {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (float)leading {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (PythagorasFRectangle *)lineBoundsWithInt:(int)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (int)lineCount {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynCoreAbstractTextLayout *typedCopy = (PlaynCoreAbstractTextLayout *) copy;
  typedCopy.format_ = format__;
  typedCopy.pad = pad_;
  typedCopy.width_ = width__;
  typedCopy.height_ = height__;
}

@end
