//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/Image.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCoreImage_RESTRICT
#define PlaynCoreImage_INCLUDE_ALL 1
#endif
#undef PlaynCoreImage_RESTRICT
#if PlaynCoreImage_Region_INCLUDE
#define PlaynCoreImage_INCLUDE 1
#endif

#if !defined (_PlaynCoreImage_) && (PlaynCoreImage_INCLUDE_ALL || PlaynCoreImage_INCLUDE)
#define _PlaynCoreImage_

@class IOSIntArray;
@class PlaynCoreGlScale;
@protocol PlaynCoreImage_BitmapTransformer;
@protocol PlaynCoreImage_Region;
@protocol PlaynCorePattern;
@protocol PlaynCoreUtilCallback;

@protocol PlaynCoreImage < NSObject, JavaObject >
- (float)width;
- (float)height;
- (PlaynCoreGlScale *)scale__;
- (BOOL)isReady;
- (void)addCallbackWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)callback;
- (BOOL)repeatX;
- (BOOL)repeatY;
- (void)setRepeatWithBOOL:(BOOL)repeatX
                 withBOOL:(BOOL)repeatY;
- (id<PlaynCoreImage_Region>)subImageWithFloat:(float)x
                                     withFloat:(float)y
                                     withFloat:(float)width
                                     withFloat:(float)height;
- (id<PlaynCorePattern>)toPattern;
- (void)getRgbWithInt:(int)startX
              withInt:(int)startY
              withInt:(int)width
              withInt:(int)height
         withIntArray:(IOSIntArray *)rgbArray
              withInt:(int)offset
              withInt:(int)scanSize;
- (id<PlaynCoreImage>)transformWithPlaynCoreImage_BitmapTransformer:(id<PlaynCoreImage_BitmapTransformer>)xform;
- (void)setMipmappedWithBOOL:(BOOL)mipmapped;
- (int)ensureTexture;
- (void)clearTexture;
@end
#endif

#if !defined (_PlaynCoreImage_Region_) && (PlaynCoreImage_INCLUDE_ALL || PlaynCoreImage_Region_INCLUDE)
#define _PlaynCoreImage_Region_

@protocol PlaynCoreImage_Region < PlaynCoreImage, NSObject, JavaObject >
- (float)x;
- (float)y;
- (void)setBoundsWithFloat:(float)x
                 withFloat:(float)y
                 withFloat:(float)width
                 withFloat:(float)height;
- (id<PlaynCoreImage>)parent;
@end
#endif

#if !defined (_PlaynCoreImage_BitmapTransformer_) && (PlaynCoreImage_INCLUDE_ALL || PlaynCoreImage_BitmapTransformer_INCLUDE)
#define _PlaynCoreImage_BitmapTransformer_

@protocol PlaynCoreImage_BitmapTransformer < NSObject, JavaObject >
@end
#endif
