//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/Pointer.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCorePointer_RESTRICT
#define PlaynCorePointer_INCLUDE_ALL 1
#endif
#undef PlaynCorePointer_RESTRICT
#if PlaynCorePointer_Adapter_INCLUDE
#define PlaynCorePointer_Listener_INCLUDE 1
#endif
#if PlaynCorePointer_Event_Impl_INCLUDE
#define PlaynCorePointer_Event_INCLUDE 1
#endif

#if !defined (_PlaynCorePointer_) && (PlaynCorePointer_INCLUDE_ALL || PlaynCorePointer_INCLUDE)
#define _PlaynCorePointer_

@protocol PlaynCorePointer_Listener;

@protocol PlaynCorePointer < NSObject, JavaObject >
- (BOOL)isEnabled;
- (void)setEnabledWithBOOL:(BOOL)enabled;
- (id<PlaynCorePointer_Listener>)listener;
- (void)setListenerWithPlaynCorePointer_Listener:(id<PlaynCorePointer_Listener>)listener;
- (void)cancelLayerDrags;
@end
#endif

#if !defined (_PlaynCorePointer_Event_) && (PlaynCorePointer_INCLUDE_ALL || PlaynCorePointer_Event_INCLUDE)
#define _PlaynCorePointer_Event_

#define PlaynCoreEvents_RESTRICT 1
#define PlaynCoreEvents_Position_INCLUDE 1
#include "playn/core/Events.h"

@protocol PlaynCorePointer_Event < PlaynCoreEvents_Position, NSObject, JavaObject >
- (BOOL)isTouch;
@end
#endif

#if !defined (_PlaynCorePointer_Event_Impl_) && (PlaynCorePointer_INCLUDE_ALL || PlaynCorePointer_Event_Impl_INCLUDE)
#define _PlaynCorePointer_Event_Impl_

@protocol PlaynCoreEvents_Flags;
@protocol PlaynCoreLayer;

#define PlaynCoreEvents_RESTRICT 1
#define PlaynCoreEvents_Position_Impl_INCLUDE 1
#include "playn/core/Events.h"

@interface PlaynCorePointer_Event_Impl : PlaynCoreEvents_Position_Impl < PlaynCorePointer_Event > {
 @public
  BOOL isTouch__;
}

@property (nonatomic, assign) BOOL isTouch_;

- (id)initWithPlaynCoreEvents_Flags:(id<PlaynCoreEvents_Flags>)flags
                         withDouble:(double)time
                          withFloat:(float)x
                          withFloat:(float)y
                           withBOOL:(BOOL)isTouch;
- (PlaynCorePointer_Event_Impl *)localizeWithPlaynCoreLayer:(id<PlaynCoreLayer>)hit;
- (BOOL)isTouch;
- (id)initWithPlaynCoreLayer:(id<PlaynCoreLayer>)hit
   withPlaynCoreEvents_Flags:(id<PlaynCoreEvents_Flags>)flags
                  withDouble:(double)time
                   withFloat:(float)x
                   withFloat:(float)y
                    withBOOL:(BOOL)isTouch;
- (NSString *)name;
@end
#endif

#if !defined (_PlaynCorePointer_Listener_) && (PlaynCorePointer_INCLUDE_ALL || PlaynCorePointer_Listener_INCLUDE)
#define _PlaynCorePointer_Listener_

@protocol PlaynCorePointer_Event;

@protocol PlaynCorePointer_Listener < NSObject, JavaObject >
- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
@end
#endif

#if !defined (_PlaynCorePointer_Adapter_) && (PlaynCorePointer_INCLUDE_ALL || PlaynCorePointer_Adapter_INCLUDE)
#define _PlaynCorePointer_Adapter_

@protocol PlaynCorePointer_Event;

@interface PlaynCorePointer_Adapter : NSObject < PlaynCorePointer_Listener > {
}

- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event;
- (id)init;
@end
#endif
