//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/TouchStub.java
//
//  Created by Thomas on 7/25/13.
//

#include "playn/core/TouchStub.h"

@implementation PlaynCoreTouchStub

- (BOOL)hasTouch {
  return NO;
}

- (id)init {
  return [super init];
}

@end
