//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/json/JsonImpl.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCoreJsonJsonImpl_RESTRICT
#define PlaynCoreJsonJsonImpl_INCLUDE_ALL 1
#endif
#undef PlaynCoreJsonJsonImpl_RESTRICT

#if !defined (_PlaynCoreJsonJsonImpl_) && (PlaynCoreJsonJsonImpl_INCLUDE_ALL || PlaynCoreJsonJsonImpl_INCLUDE)
#define _PlaynCoreJsonJsonImpl_

@protocol PlaynCoreJson_Array;
@protocol PlaynCoreJson_Object;
@protocol PlaynCoreJson_Writer;

#define PlaynCoreJson_RESTRICT 1
#define PlaynCoreJson_INCLUDE 1
#include "playn/core/Json.h"

@interface PlaynCoreJsonJsonImpl : NSObject < PlaynCoreJson > {
}

- (id<PlaynCoreJson_Writer>)newWriter OBJC_METHOD_FAMILY_NONE;
- (id<PlaynCoreJson_Array>)createArray;
- (id<PlaynCoreJson_Object>)createObject;
- (BOOL)isArrayWithId:(id)o;
- (BOOL)isObjectWithId:(id)o;
- (id<PlaynCoreJson_Object>)parseWithNSString:(NSString *)json;
- (id<PlaynCoreJson_Array>)parseArrayWithNSString:(NSString *)json;
+ (void)checkJsonTypeWithId:(id)value;
- (id)init;
@end
#endif
