//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/util/Clock.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PlaynCoreUtilClock_RESTRICT
#define PlaynCoreUtilClock_INCLUDE_ALL 1
#endif
#undef PlaynCoreUtilClock_RESTRICT
#if PlaynCoreUtilClock_Source_INCLUDE
#define PlaynCoreUtilClock_INCLUDE 1
#endif

#if !defined (_PlaynCoreUtilClock_) && (PlaynCoreUtilClock_INCLUDE_ALL || PlaynCoreUtilClock_INCLUDE)
#define _PlaynCoreUtilClock_

@protocol PlaynCoreUtilClock < NSObject, JavaObject >
- (float)time;
- (float)dt;
- (float)alpha;
@end
#endif

#if !defined (_PlaynCoreUtilClock_Source_) && (PlaynCoreUtilClock_INCLUDE_ALL || PlaynCoreUtilClock_Source_INCLUDE)
#define _PlaynCoreUtilClock_Source_

@interface PlaynCoreUtilClock_Source : NSObject < PlaynCoreUtilClock > {
 @public
  int updateRate_;
  int elapsed_;
  float current_, paintDelta_, alpha__;
}

@property (nonatomic, assign) int updateRate;
@property (nonatomic, assign) int elapsed;
@property (nonatomic, assign) float current;
@property (nonatomic, assign) float paintDelta;
@property (nonatomic, assign) float alpha_;

- (id)initWithInt:(int)updateRate;
- (float)time;
- (float)dt;
- (float)alpha;
- (void)updateWithInt:(int)delta;
- (void)paintWithFloat:(float)alpha;
@end
#endif
