//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/AbstractCircle.java
//
//  Created by Thomas on 7/25/13.
//

#include "pythagoras/d/AbstractCircle.h"
#include "pythagoras/d/Circle.h"
#include "pythagoras/d/ICircle.h"
#include "pythagoras/d/IPoint.h"
#include "pythagoras/d/Points.h"
#include "pythagoras/util/Platform.h"

@implementation PythagorasDAbstractCircle

- (BOOL)intersectsWithPythagorasDICircle:(id<PythagorasDICircle>)c {
  double maxDist = [self radius] + [((id<PythagorasDICircle>) nil_chk(c)) radius];
  return [PythagorasDPoints distanceSqWithDouble:[self x] withDouble:[self y] withDouble:[((id<PythagorasDICircle>) nil_chk(c)) x] withDouble:[((id<PythagorasDICircle>) nil_chk(c)) y]] < (maxDist * maxDist);
}

- (BOOL)containsWithPythagorasDIPoint:(id<PythagorasDIPoint>)p {
  double r = [self radius];
  return [PythagorasDPoints distanceSqWithDouble:[self x] withDouble:[self y] withDouble:[((id<PythagorasDIPoint>) nil_chk(p)) x] withDouble:[((id<PythagorasDIPoint>) nil_chk(p)) y]] < r * r;
}

- (BOOL)containsWithDouble:(double)x
                withDouble:(double)y {
  double r = [self radius];
  return [PythagorasDPoints distanceSqWithDouble:[self x] withDouble:[self y] withDouble:x withDouble:y] < r * r;
}

- (PythagorasDCircle *)offsetWithDouble:(double)x
                             withDouble:(double)y {
  return [[PythagorasDCircle alloc] initWithDouble:[self x] + x withDouble:[self y] + y withDouble:[self radius]];
}

- (PythagorasDCircle *)offsetWithDouble:(double)x
                             withDouble:(double)y
                  withPythagorasDCircle:(PythagorasDCircle *)result {
  (void) [((PythagorasDCircle *) nil_chk(result)) setWithDouble:[self x] + x withDouble:[self y] + y withDouble:[self radius]];
  return result;
}

- (PythagorasDCircle *)clone {
  return [[PythagorasDCircle alloc] initWithPythagorasDICircle:self];
}

- (BOOL)isEqual:(id)obj {
  if (obj == self) {
    return YES;
  }
  if ([obj isKindOfClass:[PythagorasDAbstractCircle class]]) {
    PythagorasDAbstractCircle *c = (PythagorasDAbstractCircle *) obj;
    return [self x] == [((PythagorasDAbstractCircle *) nil_chk(c)) x] && [self y] == [((PythagorasDAbstractCircle *) nil_chk(c)) y] && [self radius] == [((PythagorasDAbstractCircle *) nil_chk(c)) radius];
  }
  return NO;
}

- (NSUInteger)hash {
  return [PythagorasUtilPlatform hashCodeWithDouble:[self x]] ^ [PythagorasUtilPlatform hashCodeWithDouble:[self y]] ^ [PythagorasUtilPlatform hashCodeWithDouble:[self radius]];
}

- (double)radius {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)x {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)y {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id)init {
  return [super init];
}

@end
