//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/AbstractQuadCurve.java
//
//  Created by Thomas on 7/25/13.
//

#include "IOSDoubleArray.h"
#include "java/lang/Math.h"
#include "java/util/NoSuchElementException.h"
#include "pythagoras/d/AbstractQuadCurve.h"
#include "pythagoras/d/Crossing.h"
#include "pythagoras/d/FlatteningPathIterator.h"
#include "pythagoras/d/IPoint.h"
#include "pythagoras/d/IQuadCurve.h"
#include "pythagoras/d/IRectangle.h"
#include "pythagoras/d/Lines.h"
#include "pythagoras/d/PathIterator.h"
#include "pythagoras/d/Point.h"
#include "pythagoras/d/QuadCurve.h"
#include "pythagoras/d/QuadCurves.h"
#include "pythagoras/d/Rectangle.h"
#include "pythagoras/d/Transform.h"

@implementation PythagorasDAbstractQuadCurve

- (PythagorasDPoint *)p1 {
  return [[PythagorasDPoint alloc] initWithDouble:[self x1] withDouble:[self y1]];
}

- (PythagorasDPoint *)ctrlP {
  return [[PythagorasDPoint alloc] initWithDouble:[self ctrlX] withDouble:[self ctrlY]];
}

- (PythagorasDPoint *)p2 {
  return [[PythagorasDPoint alloc] initWithDouble:[self x2] withDouble:[self y2]];
}

- (double)flatnessSq {
  return [PythagorasDLines pointSegDistSqWithDouble:[self ctrlX] withDouble:[self ctrlY] withDouble:[self x1] withDouble:[self y1] withDouble:[self x2] withDouble:[self y2]];
}

- (double)flatness {
  return [PythagorasDLines pointSegDistWithDouble:[self ctrlX] withDouble:[self ctrlY] withDouble:[self x1] withDouble:[self y1] withDouble:[self x2] withDouble:[self y2]];
}

- (void)subdivideWithPythagorasDQuadCurve:(PythagorasDQuadCurve *)left
                 withPythagorasDQuadCurve:(PythagorasDQuadCurve *)right {
  [PythagorasDQuadCurves subdivideWithPythagorasDIQuadCurve:self withPythagorasDQuadCurve:left withPythagorasDQuadCurve:right];
}

- (PythagorasDQuadCurve *)clone {
  return [[PythagorasDQuadCurve alloc] initWithDouble:[self x1] withDouble:[self y1] withDouble:[self ctrlX] withDouble:[self ctrlY] withDouble:[self x2] withDouble:[self y2]];
}

- (BOOL)isEmpty {
  return YES;
}

- (BOOL)containsWithDouble:(double)px
                withDouble:(double)py {
  return [PythagorasDCrossing isInsideEvenOddWithInt:[PythagorasDCrossing crossShapeWithPythagorasDIShape:self withDouble:px withDouble:py]];
}

- (BOOL)containsWithDouble:(double)rx
                withDouble:(double)ry
                withDouble:(double)rw
                withDouble:(double)rh {
  int cross = [PythagorasDCrossing intersectShapeWithPythagorasDIShape:self withDouble:rx withDouble:ry withDouble:rw withDouble:rh];
  return cross != PythagorasDCrossing_CROSSING && [PythagorasDCrossing isInsideEvenOddWithInt:cross];
}

- (BOOL)containsWithPythagorasDIPoint:(id<PythagorasDIPoint>)p {
  return [self containsWithDouble:[((id<PythagorasDIPoint>) nil_chk(p)) x] withDouble:[((id<PythagorasDIPoint>) nil_chk(p)) y]];
}

- (BOOL)containsWithPythagorasDIRectangle:(id<PythagorasDIRectangle>)r {
  return [self containsWithDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) x] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) y] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) width] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) height]];
}

- (BOOL)intersectsWithDouble:(double)rx
                  withDouble:(double)ry
                  withDouble:(double)rw
                  withDouble:(double)rh {
  int cross = [PythagorasDCrossing intersectShapeWithPythagorasDIShape:self withDouble:rx withDouble:ry withDouble:rw withDouble:rh];
  return cross == PythagorasDCrossing_CROSSING || [PythagorasDCrossing isInsideEvenOddWithInt:cross];
}

- (BOOL)intersectsWithPythagorasDIRectangle:(id<PythagorasDIRectangle>)r {
  return [self intersectsWithDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) x] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) y] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) width] withDouble:[((id<PythagorasDIRectangle>) nil_chk(r)) height]];
}

- (PythagorasDRectangle *)bounds {
  return [self boundsWithPythagorasDRectangle:[[PythagorasDRectangle alloc] init]];
}

- (PythagorasDRectangle *)boundsWithPythagorasDRectangle:(PythagorasDRectangle *)target {
  double x1 = [self x1], y1 = [self y1], x2 = [self x2], y2 = [self y2];
  double ctrlx = [self ctrlX], ctrly = [self ctrlY];
  double rx0 = [JavaLangMath minWithDouble:[JavaLangMath minWithDouble:x1 withDouble:x2] withDouble:ctrlx];
  double ry0 = [JavaLangMath minWithDouble:[JavaLangMath minWithDouble:y1 withDouble:y2] withDouble:ctrly];
  double rx1 = [JavaLangMath maxWithDouble:[JavaLangMath maxWithDouble:x1 withDouble:x2] withDouble:ctrlx];
  double ry1 = [JavaLangMath maxWithDouble:[JavaLangMath maxWithDouble:y1 withDouble:y2] withDouble:ctrly];
  [((PythagorasDRectangle *) nil_chk(target)) setBoundsWithDouble:rx0 withDouble:ry0 withDouble:rx1 - rx0 withDouble:ry1 - ry0];
  return target;
}

- (id<PythagorasDPathIterator>)pathIteratorWithPythagorasDTransform:(id<PythagorasDTransform>)t {
  return [[PythagorasDAbstractQuadCurve_Iterator alloc] initWithPythagorasDIQuadCurve:self withPythagorasDTransform:t];
}

- (id<PythagorasDPathIterator>)pathIteratorWithPythagorasDTransform:(id<PythagorasDTransform>)t
                                                         withDouble:(double)flatness {
  return [[PythagorasDFlatteningPathIterator alloc] initWithPythagorasDPathIterator:[self pathIteratorWithPythagorasDTransform:t] withDouble:flatness];
}

- (double)ctrlX {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)ctrlY {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)x1 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)x2 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)y1 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)y2 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id)init {
  return [super init];
}

- (id)copyWithZone:(NSZone *)zone {
  return [self clone];
}

@end
@implementation PythagorasDAbstractQuadCurve_Iterator

@synthesize c = c_;
@synthesize t = t_;
@synthesize index = index_;

- (id)initWithPythagorasDIQuadCurve:(id<PythagorasDIQuadCurve>)q
           withPythagorasDTransform:(id<PythagorasDTransform>)t {
  if ((self = [super init])) {
    self.c = q;
    self.t = t;
  }
  return self;
}

- (int)windingRule {
  return PythagorasDPathIterator_WIND_NON_ZERO;
}

- (BOOL)isDone {
  return (index_ > 1);
}

- (void)next {
  index_++;
}

- (int)currentSegmentWithDoubleArray:(IOSDoubleArray *)coords {
  if ([self isDone]) {
    @throw [[JavaUtilNoSuchElementException alloc] initWithNSString:@"Iterator out of bounds"];
  }
  int type;
  int count;
  if (index_ == 0) {
    type = PythagorasDPathIterator_SEG_MOVETO;
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:0]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) x1];
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:1]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) y1];
    count = 1;
  }
  else {
    type = PythagorasDPathIterator_SEG_QUADTO;
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:0]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) ctrlX];
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:1]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) ctrlY];
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:2]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) x2];
    (*[((IOSDoubleArray *) nil_chk(coords)) doubleRefAtIndex:3]) = [((id<PythagorasDIQuadCurve>) nil_chk(c_)) y2];
    count = 2;
  }
  if (t_ != nil) {
    [t_ transformWithDoubleArray:coords withInt:0 withDoubleArray:coords withInt:0 withInt:count];
  }
  return type;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PythagorasDAbstractQuadCurve_Iterator *typedCopy = (PythagorasDAbstractQuadCurve_Iterator *) copy;
  typedCopy.c = c_;
  typedCopy.t = t_;
  typedCopy.index = index_;
}

@end
