//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/AbstractCubicCurve.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasDAbstractCubicCurve_RESTRICT
#define PythagorasDAbstractCubicCurve_INCLUDE_ALL 1
#endif
#undef PythagorasDAbstractCubicCurve_RESTRICT

#if !defined (_PythagorasDAbstractCubicCurve_) && (PythagorasDAbstractCubicCurve_INCLUDE_ALL || PythagorasDAbstractCubicCurve_INCLUDE)
#define _PythagorasDAbstractCubicCurve_

@class PythagorasDCubicCurve;
@class PythagorasDPoint;
@class PythagorasDRectangle;
@protocol PythagorasDIPoint;
@protocol PythagorasDIRectangle;
@protocol PythagorasDPathIterator;
@protocol PythagorasDTransform;

#define PythagorasDICubicCurve_RESTRICT 1
#define PythagorasDICubicCurve_INCLUDE 1
#include "pythagoras/d/ICubicCurve.h"

@interface PythagorasDAbstractCubicCurve : NSObject < PythagorasDICubicCurve > {
}

- (PythagorasDPoint *)p1;
- (PythagorasDPoint *)ctrlP1;
- (PythagorasDPoint *)ctrlP2;
- (PythagorasDPoint *)p2;
- (double)flatnessSq;
- (double)flatness;
- (void)subdivideWithPythagorasDCubicCurve:(PythagorasDCubicCurve *)left
                 withPythagorasDCubicCurve:(PythagorasDCubicCurve *)right;
- (PythagorasDCubicCurve *)clone;
- (BOOL)isEmpty;
- (BOOL)containsWithDouble:(double)px
                withDouble:(double)py;
- (BOOL)containsWithDouble:(double)rx
                withDouble:(double)ry
                withDouble:(double)rw
                withDouble:(double)rh;
- (BOOL)containsWithPythagorasDIPoint:(id<PythagorasDIPoint>)p;
- (BOOL)containsWithPythagorasDIRectangle:(id<PythagorasDIRectangle>)r;
- (BOOL)intersectsWithDouble:(double)rx
                  withDouble:(double)ry
                  withDouble:(double)rw
                  withDouble:(double)rh;
- (BOOL)intersectsWithPythagorasDIRectangle:(id<PythagorasDIRectangle>)r;
- (PythagorasDRectangle *)bounds;
- (PythagorasDRectangle *)boundsWithPythagorasDRectangle:(PythagorasDRectangle *)target;
- (id<PythagorasDPathIterator>)pathIteratorWithPythagorasDTransform:(id<PythagorasDTransform>)t;
- (id<PythagorasDPathIterator>)pathIteratorWithPythagorasDTransform:(id<PythagorasDTransform>)at
                                                         withDouble:(double)flatness;
- (double)ctrlX1;
- (double)ctrlX2;
- (double)ctrlY1;
- (double)ctrlY2;
- (double)x1;
- (double)x2;
- (double)y1;
- (double)y2;
- (id)init;
- (id)copyWithZone:(NSZone *)zone;
@end
#endif

#if !defined (_PythagorasDAbstractCubicCurve_Iterator_) && (PythagorasDAbstractCubicCurve_INCLUDE_ALL || PythagorasDAbstractCubicCurve_Iterator_INCLUDE)
#define _PythagorasDAbstractCubicCurve_Iterator_

@class IOSDoubleArray;
@protocol PythagorasDICubicCurve;
@protocol PythagorasDTransform;

#define PythagorasDPathIterator_RESTRICT 1
#define PythagorasDPathIterator_INCLUDE 1
#include "pythagoras/d/PathIterator.h"

@interface PythagorasDAbstractCubicCurve_Iterator : NSObject < PythagorasDPathIterator > {
 @public
  id<PythagorasDICubicCurve> c_;
  id<PythagorasDTransform> t_;
  int index_;
}

@property (nonatomic, strong) id<PythagorasDICubicCurve> c;
@property (nonatomic, strong) id<PythagorasDTransform> t;
@property (nonatomic, assign) int index;

- (id)initWithPythagorasDICubicCurve:(id<PythagorasDICubicCurve>)c
            withPythagorasDTransform:(id<PythagorasDTransform>)t;
- (int)windingRule;
- (BOOL)isDone;
- (void)next;
- (int)currentSegmentWithDoubleArray:(IOSDoubleArray *)coords;
@end
#endif
