//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/Circle.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasDCircle_RESTRICT
#define PythagorasDCircle_INCLUDE_ALL 1
#endif
#undef PythagorasDCircle_RESTRICT

#if !defined (_PythagorasDCircle_) && (PythagorasDCircle_INCLUDE_ALL || PythagorasDCircle_INCLUDE)
#define _PythagorasDCircle_

@protocol PythagorasDICircle;
@protocol PythagorasDIPoint;

#define PythagorasDAbstractCircle_RESTRICT 1
#define PythagorasDAbstractCircle_INCLUDE 1
#include "pythagoras/d/AbstractCircle.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@interface PythagorasDCircle : PythagorasDAbstractCircle < JavaIoSerializable > {
 @public
  double x__;
  double y__;
  double radius__;
}

@property (nonatomic, assign) double x_;
@property (nonatomic, assign) double y_;
@property (nonatomic, assign) double radius_;

- (id)init;
- (id)initWithDouble:(double)x
          withDouble:(double)y
          withDouble:(double)radius;
- (id)initWithPythagorasDIPoint:(id<PythagorasDIPoint>)p
                     withDouble:(double)radius;
- (id)initWithPythagorasDICircle:(id<PythagorasDICircle>)c;
- (PythagorasDCircle *)setWithPythagorasDICircle:(id<PythagorasDICircle>)c;
- (PythagorasDCircle *)setWithDouble:(double)x
                          withDouble:(double)y
                          withDouble:(double)radius;
- (double)x;
- (double)y;
- (double)radius;
@end
#endif
