//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/CrossingHelper.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasDCrossingHelper_RESTRICT
#define PythagorasDCrossingHelper_INCLUDE_ALL 1
#endif
#undef PythagorasDCrossingHelper_RESTRICT

#if !defined (_PythagorasDCrossingHelper_) && (PythagorasDCrossingHelper_INCLUDE_ALL || PythagorasDCrossingHelper_INCLUDE)
#define _PythagorasDCrossingHelper_

@class IOSDoubleArray;
@class IOSIntArray;
@class IOSObjectArray;
@class PythagorasDCrossingHelper_Edge;
@protocol JavaUtilList;

@interface PythagorasDCrossingHelper : NSObject {
 @public
  IOSObjectArray *coords_;
  IOSIntArray *sizes_;
  id<JavaUtilList> isectPoints_;
}

@property (nonatomic, strong) IOSObjectArray *coords;
@property (nonatomic, strong) IOSIntArray *sizes;
@property (nonatomic, strong) id<JavaUtilList> isectPoints;

- (id)initWithDoubleArray2:(IOSObjectArray *)coords
              withIntArray:(IOSIntArray *)sizes;
- (IOSObjectArray *)findCrossing;
- (BOOL)removeEdgeWithJavaUtilList:(id<JavaUtilList>)edges
                           withInt:(int)begIndex
                           withInt:(int)endIndex;
- (void)intersectShapeWithJavaUtilList:(id<JavaUtilList>)edges
                       withDoubleArray:(IOSDoubleArray *)coords1
                               withInt:(int)length1
                       withDoubleArray:(IOSDoubleArray *)coords2
                               withInt:(int)length2
    withPythagorasDCrossingHelper_Edge:(PythagorasDCrossingHelper_Edge *)initEdge;
+ (void)sortWithDoubleArray:(IOSDoubleArray *)coords1
                    withInt:(int)length1
            withDoubleArray:(IOSDoubleArray *)coords2
                    withInt:(int)length2
               withIntArray:(IOSIntArray *)array;
- (BOOL)containsPointWithDoubleArray:(IOSDoubleArray *)point;
+ (int)compareWithDouble:(double)x1
              withDouble:(double)y1
              withDouble:(double)x2
              withDouble:(double)y2;
@end
#endif

#if !defined (_PythagorasDCrossingHelper_Edge_) && (PythagorasDCrossingHelper_INCLUDE_ALL || PythagorasDCrossingHelper_Edge_INCLUDE)
#define _PythagorasDCrossingHelper_Edge_

@interface PythagorasDCrossingHelper_Edge : NSObject {
 @public
  int begIndex_;
  int endIndex_;
  int areaNumber_;
}

@property (nonatomic, assign) int begIndex;
@property (nonatomic, assign) int endIndex;
@property (nonatomic, assign) int areaNumber;

- (id)initWithInt:(int)begIndex
          withInt:(int)endIndex
          withInt:(int)areaNumber;
- (BOOL)reverseCompareWithInt:(int)begIndex
                      withInt:(int)endIndex;
@end
#endif
