//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/IllegalPathStateException.java
//
//  Created by Thomas on 7/25/13.
//

#include "pythagoras/d/IllegalPathStateException.h"

@implementation PythagorasDIllegalPathStateException

- (id)init {
  return [super init];
}

- (id)initWithNSString:(NSString *)s {
  return [super initWithNSString:s];
}

@end
