//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/IRoundRectangle.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasDIRoundRectangle_RESTRICT
#define PythagorasDIRoundRectangle_INCLUDE_ALL 1
#endif
#undef PythagorasDIRoundRectangle_RESTRICT

#if !defined (_PythagorasDIRoundRectangle_) && (PythagorasDIRoundRectangle_INCLUDE_ALL || PythagorasDIRoundRectangle_INCLUDE)
#define _PythagorasDIRoundRectangle_

@class PythagorasDRoundRectangle;

#define PythagorasDIRectangularShape_RESTRICT 1
#define PythagorasDIRectangularShape_INCLUDE 1
#include "pythagoras/d/IRectangularShape.h"

@protocol PythagorasDIRoundRectangle < PythagorasDIRectangularShape, NSCopying, NSObject, JavaObject >
- (double)arcWidth;
- (double)arcHeight;
- (PythagorasDRoundRectangle *)clone;
- (id)copyWithZone:(NSZone *)zone;
@end
#endif
