//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/Line.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !PythagorasDLine_RESTRICT
#define PythagorasDLine_INCLUDE_ALL 1
#endif
#undef PythagorasDLine_RESTRICT

#if !defined (_PythagorasDLine_) && (PythagorasDLine_INCLUDE_ALL || PythagorasDLine_INCLUDE)
#define _PythagorasDLine_

@protocol PythagorasDIPoint;

#define PythagorasDAbstractLine_RESTRICT 1
#define PythagorasDAbstractLine_INCLUDE 1
#include "pythagoras/d/AbstractLine.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@interface PythagorasDLine : PythagorasDAbstractLine < JavaIoSerializable > {
 @public
  double x1__;
  double y1__;
  double x2__;
  double y2__;
}

@property (nonatomic, assign) double x1_;
@property (nonatomic, assign) double y1_;
@property (nonatomic, assign) double x2_;
@property (nonatomic, assign) double y2_;

- (id)init;
- (id)initWithDouble:(double)x1
          withDouble:(double)y1
          withDouble:(double)x2
          withDouble:(double)y2;
- (id)initWithPythagorasDIPoint:(id<PythagorasDIPoint>)p1
          withPythagorasDIPoint:(id<PythagorasDIPoint>)p2;
- (void)setLineWithDouble:(double)x1
               withDouble:(double)y1
               withDouble:(double)x2
               withDouble:(double)y2;
- (void)setLineWithPythagorasDIPoint:(id<PythagorasDIPoint>)p1
               withPythagorasDIPoint:(id<PythagorasDIPoint>)p2;
- (double)x1;
- (double)y1;
- (double)x2;
- (double)y2;
@end
#endif
