//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/bgs/CenteredImageBackground.java
//
//  Created by Thomas on 7/25/13.
//

#import "JreEmulation.h"

#if !TripleplayUiBgsCenteredImageBackground_RESTRICT
#define TripleplayUiBgsCenteredImageBackground_INCLUDE_ALL 1
#endif
#undef TripleplayUiBgsCenteredImageBackground_RESTRICT

#if !defined (_TripleplayUiBgsCenteredImageBackground_) && (TripleplayUiBgsCenteredImageBackground_INCLUDE_ALL || TripleplayUiBgsCenteredImageBackground_INCLUDE)
#define _TripleplayUiBgsCenteredImageBackground_

@class TripleplayUiBackground_Instance;
@protocol PlaynCoreImage;
@protocol PythagorasFIDimension;

#define TripleplayUiBackground_RESTRICT 1
#define TripleplayUiBackground_INCLUDE 1
#include "tripleplay/ui/Background.h"

@interface TripleplayUiBgsCenteredImageBackground : TripleplayUiBackground {
 @public
  id<PlaynCoreImage> _image_;
}

@property (nonatomic, strong) id<PlaynCoreImage> _image;

- (id)initWithPlaynCoreImage:(id<PlaynCoreImage>)image;
- (TripleplayUiBackground_Instance *)instantiateWithPythagorasFIDimension:(id<PythagorasFIDimension>)size;
@end
#endif

#if !defined (_TripleplayUiBgsCenteredImageBackground_$1_) && (TripleplayUiBgsCenteredImageBackground_INCLUDE_ALL || TripleplayUiBgsCenteredImageBackground_$1_INCLUDE)
#define _TripleplayUiBgsCenteredImageBackground_$1_

@class TripleplayUiBgsCenteredImageBackground;
@protocol PlaynCoreSurface;

#define PlaynCoreImmediateLayer_RESTRICT 1
#define PlaynCoreImmediateLayer_Renderer_INCLUDE 1
#include "playn/core/ImmediateLayer.h"

@interface TripleplayUiBgsCenteredImageBackground_$1 : NSObject < PlaynCoreImmediateLayer_Renderer > {
 @public
  TripleplayUiBgsCenteredImageBackground *this$0_;
  float val$x_;
  float val$y_;
}

@property (nonatomic, strong) TripleplayUiBgsCenteredImageBackground *this$0;
@property (nonatomic, assign) float val$x;
@property (nonatomic, assign) float val$y;

- (void)renderWithPlaynCoreSurface:(id<PlaynCoreSurface>)surf;
- (id)initWithTripleplayUiBgsCenteredImageBackground:(TripleplayUiBgsCenteredImageBackground *)outer$
                                           withFloat:(float)capture$0
                                           withFloat:(float)capture$1;
@end
#endif
